### ISSUE TITLE
Impossible de déclarer une garde alternée

### ISSUE THREAD

**Issue by stephanecolson** [sgmap/mes-aides-ui#1]
Bonjour,

je viens d'essayer http://mes-aides.gouv.fr, il n'est pas possible de déclarer un enfant en garde alternée qui n'est donc à charge que la moitié du temps (soit 1/4 de part il me semble pour l'administration fiscale).

bon courage
PS: en fin de formulaire j'ai eu droit à "Une erreur est survenue."

**Comment by nanocom** [comment]
On peut maintenant déclarer des enfants en garde alternée :)

**Comment by stephanecolson** [comment]
Merci je vais le tester

**Comment by stephanecolson** [comment]
Désolé du délai, mais j'ai enfin retesté mon cas (je m'en suis ressouvenu en écoutant la conf de Pierre Pezziardi aujourd'hui à MixIT). Ca me dit que j'ai droit à 130€ d'allocation familiale, mais la CAF m'a confirmé que non. En effet, ce n'est (en métropole, il y a une exception dans les DOM) qu'à partir d'1 part (2 enfants à charge) qu'on y a droit. Moi j'ai un enfant à charge (1/2) et un autre en garde alternée (1/4), soit 3/4.

**Comment by MattiSG** [comment]
Bonjour Stéphane,

Merci de ton essai ! Je vais te créer un compte sur notre [outil de test](https://mes-aides.gouv.fr/tests/), afin que tu puisses nous transmettre ta situation et que nous puissions corriger le calcul  :)
Peux-tu m'envoyer un mail à <mon prénom>@data.gouv.fr avec l'adresse email que tu souhaites utiliser pour ce compte ? Merci !

Bon dimanche,
Matti

**Comment by stephanecolson** [comment]
J'ai créé le test suivant: https://mes-aides.gouv.fr/tests/553695fc5a5c6d762da9ba5a/show

**Comment by fpagnoux** [comment]
L'issue principale de la déclaration de la garde alternée étant résolue, je ferme et j'ouvre une [issue spécifique] (sgmap/openfisca-france#27) sur la prise en compte de la garde alternée dans les AF.

**Comment by HelaG** [comment]
@stephanecolson on a avancé sur la [prise en compte de la garde alternée dans les allocations familiales] (https://github.com/sgmap/openfisca-france/issues/27). 
On a sollicité des experts de la sécurité sociale qui nous ont expliqué que, quelque soit le mode de garde, un foyer avec 2 enfants est éligible aux allocation familiales. Les conditions de garde entrent en compte que dans la répartition du montant d'allocations familiales entre les parents.
Merci encore pour ta contribution et si tu as d'autres retours, n'hésites pas ;)
