### ISSUE TITLE
Permettre la capture des revenus n-2 sous IE

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#106]
En tant qu’usager éligible à aucune aide ayant fourni mon revenu n-2,
Je peux avoir une conclusion d’inéligibilité,
Pour clore mon interaction avec le produit

- - - -

Aujourd’hui, on boucle sur la capture des revenus n-2. Probablement une simple condition non remplie.

**Comment by fpagnoux** [comment]
Reproductible sur IE11, pas sur Chrome ni Firefox

**Comment by MattiSG** [comment]
Reproductible également sous IE10.

**Comment by MattiSG** [comment]
La logique est bonne dans les autres navigateurs, si la condition n’est pas évaluée correctement sous IE cela signifie que le problème se situe plutôt dans Angular.
Nous sommes en retard au niveau des versions d’Angular, le coût de mise à jour sera non négligeable, surtout sans tests d’intégration.

Le problème étant limité aux personnes non éligibles et sous IE, je renomme le bug et en diminue la priorité.

**Comment by MattiSG** [comment]
Elle est « prête à implémenter » car le problème a été reproduit et que la solution est connue… C’est le problème d’un processus qui laisse des étapes intermédiaires de stockage  ;)

On en reparle mardi ou mercredi.

**Comment by MattiSG** [comment]
+1 UDAF 92.

En réalité, c'est la capture des revenus n-2 qui n'est pas fonctionnelle sous IE11… Plus important que prévu, donc.

**Comment by MattiSG** [comment]
Reproductible sous Edge/Win10.

+1 mail du 05/10/2015 à 19:05

**Comment by MattiSG** [comment]
Le problème disparaît lorsque les outils développeurs d’Internet Explorer sont ouverts. 
![capture d ecran 2015-10-09 a 18 49 16](https://cloud.githubusercontent.com/assets/222463/10400043/cdba5c50-6eb6-11e5-99f6-98b4c705f482.png)
> J'avoue avoir un peu envie de pleurer.

**Comment by MattiSG** [comment]
État actuel des investigations :

- Le problème disparaît lorsque les outils développeur sont actifs. L'impact a priori est [limité à](http://stackoverflow.com/questions/7742781) l'existence de l'objet `console` sous IE9 (aucun changement au remplacement par `$log`) et à la mise en cache des requêtes `GET` (aucun changement à l'ajout d'un paramètre de cache-busting dans le `GET simulation`).
- La requête `PUT` faite pour mettre à jour la situation est correctement envoyée au serveur. Je n'ai pas encore examiné son contenu.
- L'ordre du `PUT` et du `GET` est bon.

Si la communication avec l'API est correcte, le problème devrait donc logiquement se trouver dans la constitution de l'objet `situation` envoyé à l'API. L'impact des outils développeurs devient néanmoins alors incompréhensible.

**Comment by MattiSG** [comment]
- Si je désactive le `PUT` et ne fais que systématiquement des `POST`, le problème disparaît.

L'effet de bord est qu'on crée ainsi à chaque fois une nouvelle simulation.

**Comment by davidbgk** [comment]
Le support de PUT/DELETE par les navigateurs est… limité. Est-ce qu'Angular envoie vraiment du `PUT` ou il met ça dans un `POST` + `_method=PUT` (par exemple) ?

**Comment by MattiSG** [comment]
D'après les logs du serveur Express, on reçoit bien un `PUT`. Je ne sais pas s'il utilise un unwrapping ou non, mais le routing devrait dans tous les cas se faire correctement.

**Comment by MattiSG** [comment]
Après une implémentation avec [`method-override`](https://github.com/expressjs/method-override) (utiliser du `POST` et transcrire en `PUT` sur le serveur), il s'avère que le problème n'est pas résolu.
L'origine du problème est bien la mise en cache du `GET`, et utiliser systématiquement un `POST` avait pour effet de bord de générer une nouvelle `id` à chaque fois, et donc une nouvelle url non mise en cache.
Il faut donc trouver un moyen de forcer la désactivation du cache au `GET situation` sous IE, sachant qu'un paramètre en query string ne fonctionne pas.

**Comment by MattiSG** [comment]
Correction : sans cachebust, le `GET` n'est simplement pas fait. La requête est bien faite, reste à comprendre pourquoi son contenu est ignoré par IE.

**Comment by MattiSG** [comment]
Bon sang, je l'ai. On fait deux requête distinctes, une pour la situation et l'autre pour les résultats… Il fallait cachebuster les deux.

**Comment by fpagnoux** [comment]
:tada: :dancers: :balloon: :birthday: :checkered_flag:
