### ISSUE TITLE
Ajouter la prestation Paris Logement Famille

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#109]
En tant que bénéficiaire potentiel résidant à Paris,
Je peux estimer mon éligibilité à la prestation Paris Logement Famille,
Pour compléter l'étude de mes droits

- - - - -

- [x] Capturer la condition de résidence à Paris.
- [x] Modifier "personnes à charge" -> "personnes figurant sur la dernière déclaration d'IR".
- [x] Capturer les charges sur le loyer.
- [x] Afficher la prestation.

- - - - -

- [ ] Communication Mairie de Paris
- [ ] Twitter

**Comment by Anne-LaureM** [comment]
Pas de condition d'âge pour les enfants (pour les enfants handicapés)

**Comment by Anne-LaureM** [comment]
Gérer le cas de la garde alternée

**Comment by MattiSG** [comment]
Pour la question sur l'occupation du logement, proposition à améliorer :

« Résidence principale

- Votre domicile.
- En garde alternée.
- Indépendant mais revient chez vous régulièrement. _À préciser avec le CASVP pour enlever l'ambiguïté._
- Est totalement indépendant. »

**Comment by fpagnoux** [comment]
Il y avait aussi je crois une autre condition pour les enfants handicapés: ils doivent recevoir l'AAH ou l'AEEH. A voir ce qu'on en fait.

**Comment by Anne-LaureM** [comment]
Ils doivent percevoir l’AEEH.

De : Florian Pagnoux [mailto:notifications@github.com]
Envoyé : mercredi 24 juin 2015 13:30
À : sgmap/mes-aides-ui
Cc : MICHON Anne-Laure
Objet : Re: [mes-aides-ui] Ajouter la prestation Paris Logement Famille (#109)


Il y avait aussi je crois une autre condition pour les enfants handicapés: ils doivent recevoir l'AAH ou l'AEEH. A voir ce qu'on en fait.

**Comment by MattiSG** [comment]
Retour du CASVP : la règle de la présence au domicile pour les enfants est réduite à "enfant à charge au sens du code général des impôts ou de moins de 25 ans qui est demandeur d’emploi inscrit à Pôle Emploi ou organismes similaires et non indemnisé".

**Comment by MattiSG** [comment]
Référence officielle "à charge" : http://www.paris.fr/viewmultimediadocument?multimediadocument-id=154767&ei=ce-QVZ6qH6PW7Aa_iKKgCg&usg=AFQjCNH2Sp1TjjpvktyBKT12GNKMGAx7Iw&bvm=bv.96783405,d.ZGU&cad=rja

**Comment by fpagnoux** [comment]
Je pense que la version actuelle est communicable à la mairie de Paris.  Les points qui resteront à traiter : 

- [ ] Prendre en compte la garde alternée : besoins de précisions de la mairie de Paris
- [ ] Prendre en compte les enfants handicapés  à charge de plus de 25 ans
- [ ] Découplage entre la partie Openfisca France "standard" et les aides locales (à introduire sous forme d'un plugin optionnel). C'est une demande d'Openfisca.

**Comment by Anne-LaureM** [comment]
Bonjour Florian,
Peux-tu me re-donner ton numéro de portable pour que je t’appelle ?
AL

De : Florian Pagnoux [mailto:notifications@github.com]
Envoyé : jeudi 16 juillet 2015 20:05
À : sgmap/mes-aides-ui
Cc : MICHON Anne-Laure
Objet : Re: [mes-aides-ui] Ajouter la prestation Paris Logement Famille (#109)


Je pense que la version actuelle est communicable à la mairie de Paris. Les points qui resteront à traiter :

  *   [ ] Prendre en compte la garde alternée : besoins de précisions de la mairie de Paris
  *   [ ] Prendre en compte les enfants handicapés à charge de plus de 25 ans
  *   [ ] Découplage entre la partie Openfisca France "standard" et les aides locales (à introduire sous forme d'un plugin optionnel). C'est une demande d'Openfisca.

**Comment by MattiSG** [comment]
https://twitter.com/mesaides/status/625982397738258432
