### ISSUE TITLE
Ajouter la prestation Fonds de Solidarité Logement

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#110]
En tant que bénéficiaire potentiel résidant à Paris,
Je peux estimer mon éligibilité à la prestation ponctuelle Fonds de Solidarité Logement,
Pour compléter l'étude de mes droits

- - - - -

Les AL et aides CASVP ne sont pas prises en compte dans la base ressources.
Condition : avoir contracté des aides locatives ou énergétiques, ou rencontrer des difficultés d'emménagement.

- [ ] Modifier "personnes à charge" -> "personnes vivant sous le même toit".
- [ ] Capturer les charges sur le loyer.
- [ ] Afficher la prestation dans un bloc spécifique "prestations de soutien".
- [ ] Capturer les trois derniers mois pour micro-entreprise et libéral/entrepreneur.
- [ ] Ajouter une ressource : aidant familial / allocation compensatrice pour tierce personne (ACTP), catégorie TNS.
- [ ] Ajouter une ressource : PCH (Prestation de Compensation du Handicap, allocation).
- [ ] "Retraite (y compris réversion)" -> "Retraite, réversion, complémentaire".
- [ ] Locataire -> (Sous-)locataire.
- [ ] Éclater "Meublé / hôtel" en "Meublé" / "Hôtel" (éligibilité pour meublé seulement).
- [ ] Éclater "Foyer" en "Foyer : travailleurs migrants / maisons relais" (éligible) et "Autres foyers" (non éligible).
- [ ] Capturer, dans le cas du foyer, s'il s'agit d'une chambre partagée (inéligible).
- [ ] Conditionner l'aide à la résidence à Paris.

**Comment by HelaG** [comment]
Ok pour moi!

Reste à définir le mode d'affichage de la presta en résultat = prestation "facultative" soumise à évaluation en commission. 

Option discutée: Afficher un bloc supplémentaire à la page des résultats "Le saviez-vous ? Compte tenu des informations transmises vous seriez également éligible au FSL (+ d'infos)" + disclaimer "décence" du logement comme pour les APL.

**Comment by MattiSG** [comment]
Cette prestation est différente de toutes celles traitées jusqu’à présent : son déclencheur est un événement ponctuel (une difficulté à faire face au coût du loyer, avec accumulation de dette). On ne peut donc pas l’intégrer dans le flux actuel de Mes Aides.

Les aides de ce type seront peut-être intégrées, mais dans une phase ultérieure.
