### ISSUE TITLE
Trouver le blocage à l'enregistrement d'un test

### ISSUE THREAD

**Issue by Anne-LaureM** [sgmap/mes-aides-ui#114]
Dans ce cas ci, la personne fait la simulation, entre sur la page de création de test mais ne parvient pas à cliquer sur le bouton "enregistrer" pour créer le test.

**Comment by MattiSG** [comment]
A priori sous Firefox 20.

**Comment by MattiSG** [comment]
Moved to sgmap/ludwig-ui#39.
