### ISSUE TITLE
Enlever le code mort

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#12]
#10 et #11 montrent qu'il existe des éléments de code encore versionnés qui ne sont plus utilisés. Il faudrait les enlever.

**Comment by MattiSG** [comment]
Maintenant que Ludwig a été intégré, le code frontal a-t-il été nettoyé (càd peut-on fermer cette issue) ?

**Comment by jdesboeufs** [comment]
Oui c'est bon, je ferme !
