### ISSUE TITLE
Capturer les frais réels n-2

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#125]
En tant que travailleur non salarié bénéficiaire potentiel d’aides CAF,
Je peux déclarer mes revenus et frais réels n-2,
Pour déterminer mon éligibilité à ces aides

**Comment by MattiSG** [comment]
C'est censé être implémenté, j'ai déjà vu apparaître cet écran, mais je n'arrive pas à le reproduire de manière systématique. @fpagnoux sous quelles conditions est-on censé saisir les frais réels ?

**Comment by fpagnoux** [comment]
Les frais réels sont toujours capturés dans l'écran ressources n-2. 
Le RFR est lui en revanche demandé seulement si un enfant est susceptible d'être éligible à une bourse collège ou lycée.

**Comment by fpagnoux** [comment]
Les frais réels sont toujours capturés dans l'écran ressources n-2.
Le RFR est lui en revanche demandé seulement si un enfant est susceptible
d'être éligible à une bourse collège ou lycée.

Le 22 septembre 2015 11:29, Matti Schneider <notifications@github.com> a
écrit :

**Comment by MattiSG** [comment]
Ok, merci ! Je ferme donc cette issue.
