### ISSUE TITLE
Tests routing is only valid for root

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#13]
If I try to access https://mes-aides.gouv.fr/acceptance-tests/login rather than https://mes-aides.gouv.fr/acceptance-tests with front-end routing, no scripts are loaded and, due to the SPA nature of the app, I get an unusable base page.

This seems to happen because of relative rather than absolute inclusions.

I am not sure whether this issue should be opened here or in Ludwig.

**Comment by nanocom** [comment]
is the problem still there?

**Comment by MattiSG** [comment]
Nope   :)
