### ISSUE TITLE
Ajouter la condition de présence sur le bail

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#142]
En tant que bénéficiaire potentiel des aides au logement,
Je suis informé en fin de simulation que je dois apparaître sur le bail,
Pour évaluer correctement mon éligibilité

- [x] Ajouter une condition textuelle.

**Comment by MattiSG** [comment]
@HelaG Peux-tu stp confirmer ce point au niveau réglementaire, et le détailler le cas échéant ? Merci !  :)

**Comment by HelaG** [comment]
Alors je ne trouve pas référence réglementaire concernant l'obligation de figurer sur le bail - ça ne fait pas partie des conditions indiquées [ici](http://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006743358&dateTexte=&categorieLien=cid)

Par contre, la condition est bien indiquée sur [cette page](https://www.caf.fr/aides-et-services/s-informer-sur-les-aides/logement-et-cadre-de-vie/les-aides-au-logement-0) de la caf: "Dans le cas d’une location, la quittance de loyer et le bail doivent toujours être libellés au nom de la personne qui fait la demande d’aide au logement."
