### ISSUE TITLE
Ajouter l’ADPA 93

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#147]
En tant que bénéficiaire potentiel de l’ADPA âgé de plus de 60 ans et résidant dans le 93,
Je peux découvrir ou déterminer mon éligibilité à l’ADPA,
Pour évaluer mes droits

- [x] Coder l’ADPA.
- [x] Présenter le bénéfice sous la forme d’un pourcentage de frais occasionnés par la dépendance.
- [x] Lier la démarche vers http://www.seine-saint-denis.fr/ADPA.html
- [x] Documenter la simplification : pas de prise en compte du GIR car évaluation pendant la démarche et expression du bénéfice sous la forme d’un % de frais occasionnés par la dépendance, donc si pas de frais pas de montant.
- [x] Affichage du numéro de téléphone ?
- [ ] Documenter les modalités techniques d’ajout d’une aide dans OpenFisca.

**Comment by MattiSG** [comment]
Suggestion de formulation :
![capture d ecran 2015-08-28 a 11 44 28](https://cloud.githubusercontent.com/assets/222463/9543600/5487e620-4d7a-11e5-877a-f19ca55ea6c0.png)

**Comment by fpagnoux** [comment]
Changes in UI done :)

**Comment by MattiSG** [comment]
Le code est sur quelle branche ?

**Comment by fpagnoux** [comment]
xp-adpa-93 et demo

**Comment by fpagnoux** [comment]
xp-adpa-93 et demo

**Comment by fpagnoux** [comment]
Pas de nouvelles du 93, je vais contacter Salim et je passe cette issue en 'en attente'

**Comment by fpagnoux** [comment]
Le CD93 viendra toute la journée le 25 novembre.

**Comment by MattiSG** [comment]
- [ ] Importer les tests liés à l’ADPA depuis Ludwig (base de données next).

**Comment by MattiSG** [comment]
- [ ] Lister l’ADPA [sur le wiki](https://wiki.openfisca.fr/index.php/Mes_aides#Ville_de_Paris).

**Comment by fpagnoux** [comment]
Ajouté au [wiki](https://waffle.io/sgmap/mes-aides-api/cards/55e029462013233200bc8f11)
