### ISSUE TITLE
Améliorer le déclenchement de la demande de prestations simulées

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#149]
En tant que bénéficiaire potentiel,

je peux engager mes démarches à la sortie de la simulation

pour accéder aux prestations simulées.

**Comment by HelaG** [comment]
[Retour utilisateur](https://twitter.com/CMaudry/status/639157820924010497)

**Comment by MattiSG** [comment]
Cette issue n'est pas au même niveau de granularité que les autres (il s'agit d'un [_epic_ et non d'une _story_](https://www.mountaingoatsoftware.com/blog/stories-epics-and-themes)).

Nous allons tester l'usage des milestones GitHub pour traiter les _epics_. Pour suivre l'avancée sur ce point, suivre la [milestone](https://github.com/sgmap/mes-aides-ui/milestones) « Engager les démarches ».
