### ISSUE TITLE
Migrer la prod vers pm2 + nvm

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/mes-aides-ui#151]
Vu avec Jérôme, ça diminuerait le risque de bugs en production et ça permettrait d'accéder aux logs du serveur sans se loguer en  `root`

**Comment by MattiSG** [comment]
Que signifie « migrer la prod sur NVM » ? NVM me semble faire partie de la couche inférieure, extérieure à l’appli.

Pour le gestionnaire de processus, je ne souhaite personnellement pas investir maintenant dans migrer la codebase actuelle. `rewrite` est déjà basé sur PM2. Si on a un véritable besoin urgent d’abandonner `upstart` pour la prod on le fera, mais je ne crois pas que ce soit le cas actuellement.

**Comment by guillett** [comment]
@MattiSG, puis-je fermer cet issue en considérant que ça a été rendu obsolète avec mes-aides-ops ?

**Comment by MattiSG** [comment]
Oui. Quand tu es sûr à 80% d'une décision de ce type, qui est réversible, n'hésite pas à agir en précisant les conditions sous lesquelles la décision peut être renversée :wink:
