### ISSUE TITLE
Ne pas afficher d'AL en dessous du montant de versement

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#152]
Seuil de versement de 15€

**Comment by HelaG** [comment]
(http://www.legifrance.org/affichCodeArticle.do;jsessionid=7BBDB7E1EC91EB60126C29A30B1FABDF.tpdila09v_2?idArticle=LEGIARTI000006739234&cidTexte=LEGITEXT000006073189&dateTexte=19970130&categorieLien=id&oldAction=&nbResultRech=)[Article de référence]

**Comment by fpagnoux** [comment]
Cette règle était déjà implémentée, avec un minimum de 15€.
