### ISSUE TITLE
Appliquer correctement la majoration du RSA pour isolement

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#156]
En tant que potentiel bénéficiaire,
je peux correctement estimer mon droit au RSA quand je suis en situation d’isolement.

- [x] Mettre à jour les tests pour prendre en compte la condition d’isolement.

**Comment by HelaG** [comment]
Aujourd'hui le simulateur pousse automatiquement du RSA majoré sans tenir compte de la durée de la situation d'isolement.

**Comment by HelaG** [comment]
La majoration du RSA est appliquée à #partir du mois au cours duquel survient l'"isolement" (déclaration de grossesse, naissance d'un enfant, prise en charge d'un enfant, séparation, veuvage, dépôt de la demande si l’événement est antérieur.

Le montant forfaitaire majoré peut être accordé pendant 12 mois, continus ou discontinus, au cours d’une période de 18 mois suivant l’événement.

Si votre plus jeune enfant à charge a moins de 3 ans, le montant forfaitaire majoré vous est accordé jusqu'à ses 3 ans.

Le montant forfaitaire majoré pour isolement dépend du nombre d'enfants à charge.

**Comment by HelaG** [comment]
Pour affiner l'application du RSA majoré, si la personne est seule et :
- que son enfant le plus jeune a moins de 3 ans, on applique systématiquement la majoration ;
- que son enfant le plus jeune a plus de 3 ans, on doit demander si la personne est isolée depuis moins de 18mois. Si elle isolée depuis moins de 18 mois , on pousse une majoration de RSA.

Pour poser cette question on peut inverser l'ordre de constitution de la famille : 
VOUS -> ENFANTS -> CONJOINT.

**Comment by MattiSG** [comment]
> VOUS -> ENFANTS -> CONJOINT

En demandant du coup sur la page Conjoint, si « seul », si cela fait moins de 18 mois, c’est ça  ?

**Comment by HelaG** [comment]
Oui!

**Comment by fpagnoux** [comment]
La version réordonnée est disponible pour tester sur la branche [reorder-enfants-conjoint](https://github.com/sgmap/mes-aides-ui/tree/reorder-enfants-conjoint)

**Comment by fpagnoux** [comment]
Poser une nouvelle question dans l'écran conjoint est en fait assez compliqué. On en reparle toute à l'heure ?

**Comment by fpagnoux** [comment]
C'est prêt, j'envoie les PR. Par contre, ça va casser tous les tests pour lesquels on versait à raison le RSA majoré. 
Il faudra soit les prendre un par un pour répondre à la question sur la durée de l'isolement, soit faire un script de migration s'il y en a beaucoup.

**Comment by fpagnoux** [comment]
![image](https://cloud.githubusercontent.com/assets/11834997/10096014/782f22d2-636e-11e5-9340-4642c80a5811.png)

**Comment by fpagnoux** [comment]
En attente de validation

**Comment by fpagnoux** [comment]
24 tests passent au rouge, 2 passent au vert. Je vais faire un script de migration.
