### ISSUE TITLE
Corriger le nombre de décimales des champs « total des 12 derniers mois »

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/mes-aides-ui#166]
Lorsque je veux modifier mes ressources après avoir obtenu le résultat de ma simulation, la valeur affichée dans le champ « total sur les 12 derniers mois » est affichée avec un grand nombre de décimales et est incrémentée d'une valeur mystérieuse.

**Comment by MattiSG** [comment]
Je ne reproduis pas l'incrément, seulement les décimales.

**Comment by MattiSG** [comment]
Ça touche tous les champs « 12 derniers mois », pas que les pensions alimentaires versées.

**Comment by MattiSG** [comment]
@fpagnoux Has this been closed through #328?

**Comment by fpagnoux** [comment]
Yep.
