### ISSUE TITLE
Prendre en compte les enfants handicapés de plus de 25 ans dans la définition du loyer de référence

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#169]
Correction du cas de recette Caf77 : https://mes-aides.gouv.fr/tests/559fb665f394e1a7011b573a/show?keyword=recette

L'enfant handicapé n'est pas pris en compte dans la définition du loyer de référence qui entre dans le calcul des AL.

**Comment by fpagnoux** [comment]
Est-ce qu'il y a un taux minimum d'invalidité ?

**Comment by fpagnoux** [comment]
80%  je crois : 
```
Votre enfant, après son 20ème anniversaire, peut éventuellement être pris en compte dans le calcul de vos aides au logement, si :
il est atteint d'une infirmité avec incapacité permanente au moins égale à 80 % ;
il est titulaire de la carte d'invalidité ou reconnu par la Commission des droits et de l'autonomie des personnes handicapées (Cdaph) ;
il est reconnu inapte au travail ;
ses ressources nettes imposables n'excèdent pas le plafond individuel du fonds de solidarité vieillesse.
```

**Comment by HelaG** [comment]
Les personnes à charge sont : 
- [...]
- les enfants de plus de 21 ans, les petits enfants, frères, soeurs, oncles, tantes, neveux et nièces du bénéficiaire et de son conjoint dont les ressources n'excèdent pas le montant du minimum vieillesse s'ils sont infirmes ou handicapés et inaptes au travail.

(Source) [http://www.territoires.gouv.fr/IMG/pdf/MEDDAT_Plaq_logement_2013_bd.pdf]
