### ISSUE TITLE
Référencer Mes Aides sur service-public.fr

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#170]
En tant qu'usager de service-public.fr m'informant sur une prestation spécifique,
Je suis orienté vers Mes Aides,
Pour évaluer mes droits plus facilement

---

Communication : 
- [ ] @ppezziardi
- [ ] mail du 02/10/2015 à 09:31

**Comment by monbocal** [comment]
https://www.service-public.fr/particuliers/vosdroits/R45524 ?

**Comment by MattiSG** [comment]
Pas mal, mais je ne sais pas où on cette page est référencée exactement : on n'apparaît pas dans la liste « Services en ligne » sur https://www.service-public.fr/particuliers/vosdroits/F19778, par exemple.

@akhilian comment pourrait-on avancer sur ce sujet ?  :)

**Comment by Akhilian** [comment]
Pour le coup, il s'agit d'un problème rédactionnel.
Est-ce que le lien "Faire une suggestion" pourrait suffire à signaler le manque du lien ?

Le service est référencé dans "Service en ligne et formulaire" > Simulateur
https://www.service-public.fr/particuliers/recherche?rubricFilter=serviceEnLigne&rubricTypeFilter=simulateur

**Comment by MattiSG** [comment]
@monbocal peux-tu prendre en charge la « suggestion » à faire à service-public.fr ?  :)

**Comment by monbocal** [comment]
Suite à un message à service-public.fr (à travers leur formulaire de contact), en nous présentant et en fournissant la liste des pages sur lesquelles nous souhaitions apparaître, nous apparaissons. Mes Aides est référencé dans "Services en ligne et formulaires" en bas de page, par exemple sur https://www.service-public.fr/particuliers/vosdroits/F13213 .

**Comment by MattiSG** [comment]
Nous sommes donc référencés sur :

Allocations familiales :
https://www.service-public.fr/particuliers/vosdroits/F13213

Complément familial :
https://www.service-public.fr/particuliers/vosdroits/F13214

Allocation de soutien familial :
https://www.service-public.fr/particuliers/vosdroits/F33645
https://www.service-public.fr/particuliers/vosdroits/F815
https://www.service-public.fr/particuliers/vosdroits/F33647
https://www.service-public.fr/particuliers/vosdroits/F33646
(d’ailleurs, une seule fiche globale ASF serait peut-être bienvenue pour la navigation sur votre site?)

PAJE de base :
https://www.service-public.fr/particuliers/vosdroits/F31430
https://www.service-public.fr/particuliers/vosdroits/F2552

RSA (3 des 4 sont simulés) :
https://www.service-public.fr/particuliers/vosdroits/F19778
https://www.service-public.fr/particuliers/vosdroits/F15553
https://www.service-public.fr/particuliers/vosdroits/F33692

Aides au logement :
https://www.service-public.fr/particuliers/vosdroits/F12006
https://www.service-public.fr/particuliers/vosdroits/F13132
https://www.service-public.fr/particuliers/vosdroits/F1280

Prime d’activité :
https://www.service-public.fr/particuliers/vosdroits/F2882

AAH :
https://www.service-public.fr/particuliers/vosdroits/F12242

ACS :
https://www.service-public.fr/particuliers/vosdroits/F13375

CMU-C :
https://www.service-public.fr/particuliers/vosdroits/F10027

ASI :
https://www.service-public.fr/particuliers/vosdroits/F16940

Bourse des collèges :
https://www.service-public.fr/particuliers/vosdroits/F984

Bourse de lycée :
https://www.service-public.fr/particuliers/vosdroits/F616

ASS :
https://www.service-public.fr/particuliers/vosdroits/F12484

ASPA :
https://www.service-public.fr/particuliers/vosdroits/F16871


👏 bravo @monbocal !!

**Comment by Akhilian** [comment]
Super cool 👍
