### ISSUE TITLE
Traiter l'éligibilité CMU < 25 ans

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#171]
En tant que bénéficiaire potentiel de la CMU de moins de 25 ans,
Je peux être informé des conditions spécifiques liées à mon âge,
Pour ne pas faussement croire y être éligible

[Source](https://twitter.com/mesaides/status/649911790495731712).

- - - - - -

A priori, disjonction selon l'âge : 

- < 16 ans : inéligible ;
- < 20 ans : éligible si [en rupture de liens avec la famille](http://www.ameli.fr/assures/droits-et-demarches/par-situation-professionnelle/vous-faites-des-etudes/vous-etes-lyceen/vous-avez-moins-de-20-ans.php) ;
- < 25 ans : éligible si [foyer fiscal et domicile disjoints des parents](http://www.ameli.fr/assures/droits-et-demarches/par-situation-professionnelle/vous-faites-des-etudes/vous-etes-etudiant/la-cmu-complementaire.php), et pas de perception alimentaire déductible des impôts (ou bénéficier des aides annuelles d'urgence versées par le CROUS sur le Fonds national d'aide d'urgence) ou avoir des enfants à charge

**Comment by Anne-LaureM** [comment]
Test rouge [ https://mes-aides.gouv.fr/tests/560e8022954ba9fc6e2de05e/show ]

**Comment by fpagnoux** [comment]
Je priorise ce point de fiabilité, car la cible me paraît assez large et l'erreur pas anodine.

**Comment by fpagnoux** [comment]
> #### Une demande individuelle est possible pour :

>Les enfants mineurs de plus de 16 ans ayant rompu leurs liens familiaux.
Les enfants majeurs (entre 18 et 25 ans) ne vivant plus sous le même toit que leurs parents, ayant rempli une déclaration fiscale séparée (ou s'engageant sur l'honneur et par écrit à le faire l'année suivante) et ne percevant pas de pension alimentaire donnant lieu à déduction fiscale.
Les enfants majeurs (entre 18 et 25 ans), vivant sous le même toit que leurs parents, s'ils sont eux-mêmes parents ou s'ils vont le devenir.
Les enfants mineurs de moins de 16 ans qui relèvent de l'aide sociale à l'enfance (ASE) ou de la protection judiciaire de la jeunesse (PJJ) par l'intermédiaire de ces deux organismes.
Les étudiants isolés, bénéficiant des aides annuelles d'urgence versées par les CROUS sur le Fonds national d'aide d'urgence (FNAU).
Les conjoints séparés.

[Voir plus](http://www.ameli.fr/assures/soins-et-remboursements/cmu-et-complementaires-sante/cmu-complementaire/votre-dossier-de-demande.php)

**Comment by fpagnoux** [comment]
La limite semble plutôt à 18 ans que 20 ans,.

**Comment by fpagnoux** [comment]
Je propose l'implémentation suivante: 
- Si la personne a entre 18 et 25 ans:
    - On lui demande si elle fiscalement indépendante dans la première page
    - Si elle est hebergée, on lui demande si elle vit chez ses parents
    - On prend en compte les pensions alimentaires perçues déclarées dans les ressources
- Si la personne a entre 16 et 18 ans:
    - Solution 1: Pas de CMUC, on ignore la possibilité d'une rupture.
    - Solution 2: On demande si la personne est en rupture familiale. Question violente, mais pas si absurde dans le contexte d'une personne qui fait une demande en se déclarant comme demandeur alors qu'il a 17 ans. Par contre, ce n'est pas un concept qui est clairement défini, mais établi par une assistance sociale.

@MattiSG @HelaG, wdyt ?

**Comment by MattiSG** [comment]
> On lui demande si elle fiscalement indépendante dans la première page

Ça me semble être une question pas évidente, il faudra trouver la bonne formulation.

> Question violente, mais pas si absurde dans le contexte d'une personne qui fait une demande

Je suis ok avec ça. Idem, tout le travail sera dans la formulation.
Peut-être faut-il simplement afficher un message d'information du type « Vous avez moins de 18 ans, et n'êtes donc pas directement éligible à la majorité des aides. Nous allons supposer que vous n'avez plus de liens avec vos parents. Si ce n'est pas le cas, faites une simulation du point de vue d'un de vos parents ou tuteur. » ?
