### ISSUE TITLE
Ajouter l'AAH

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#172]
En tant que bénéficiaire potentiel de l'AAH,
Je peux savoir que la prestation existe,
Pour avoir une vision à 360° de mes droits.

Comm:
- [x] Cab Neuville

**Comment by MattiSG** [comment]
Selon niveau de handicap :

- < 50% : inéligible ;
- > 80% : calcul du montant ;
- ≥50% < 80% : non-calculable car nécessite démonstration de la part de l’usager.

Pourrait être plus précis que « non-calculable » (soit montant connu soit 0), mais correspondance acceptable avec les mécanismes actuellement en place.

**Comment by HelaG** [comment]
|Pour un handicap > 80%|

**Comment by HelaG** [comment]
** Pour un handicap > 80%** 
On détermine le montant de l'aide en fonction des revenus des 3 derniers mois : 
- 807,65€ / mois pour un bénéficiaire potentiel sans revenus [source Caf] (http://www.caf.fr/aides-et-services/s-informer-sur-les-aides/solidarite-et-insertion/l-allocation-aux-adultes-handicapes-aah-0?active=tab1)

- 807,65€ - le montant mensuel de pension (invalidité, retraite, rente accident du travail) perçue pour une bénéficiaire qui ne perçoit QU'UNE pension.

- En fonction de ses revenus trimestriels s'il travaille.

**Comment by HelaG** [comment]
Après pas mal de recherche dans le [CSS](http://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006073189&idArticle=LEGIARTI000006739874&dateTexte=&categorieLien=cid) et sur les sites officiels, je trouve que l'information la plus claire sur le mode de calcul de l'AAH est celle d'un [usager](http://kevin.polisano.free.fr/?p=742#calcul)!

**Comment by HelaG** [comment]
Un bénéficiaire de l'AAH à taux plein peut aussi bénéficier d'une [majoration pour vie autonome](https://www.service-public.fr/particuliers/vosdroits/F12903) de 104,77€ par mois s'il :
- a un taux d'incapacité > 80%;
- habite dans un logement indépendant ouvrant droit aux AL;
- ne travaille pas.

**Comment by HelaG** [comment]
De même un bénéficiaire de l'AAH à taux plein peut avoir un [complément de ressources](https://www.service-public.fr/particuliers/vosdroits/F12911) de 179,32€ par mois s'il :
- a un taux d'incapacité > 80%;
- a une capacité de travail inférieure à 5% reconnue par la CDAPH;
- habite dans un logement indépendant ouvrant droit aux AL;
- ne travaille pas depuis au moins 1 an.

**Comment by HelaG** [comment]
- [ ] Créer des tests
- [ ] Faire valider les tests

**Comment by fpagnoux** [comment]
L'AAH peut maintenant être testée sur http://next.mes-aides.sgmap.fr/

**Comment by fpagnoux** [comment]
Est-ce que le complément à l'AAH que tu mentionnes doit être considéré comme une "majoration" de l'AAH ou comme une aide distincte ? 
Plus concrètement, si je suis éligible à l'AAH et au complément, est-ce que sur la page de résultat je vois seulement l'AAH OU l'AAH et son complément séparés ?

**Comment by MattiSG** [comment]
Qui peut créer / valider les tests ?

**Comment by MattiSG** [comment]
J'arrive à faire apparaître l'AAH.

En revanche, je ne peux pas la capturer dans les ressources.

**Comment by HelaG** [comment]
Je créée les tests et je demande validation à l'usager expert + un expert IMPACT.

**Comment by MattiSG** [comment]
:+1:

**Comment by fpagnoux** [comment]
Tu ne peux pas capturer l'AAH ou l'AEEH ?

**Comment by MattiSG** [comment]
Ahem… Je n'avais juste pas les yeux en face des trous, je peux capturer l'AAH.

En revanche, si je la déclare, elle est recalculée.
![capture d ecran 2015-11-12 a 16 22 47](https://cloud.githubusercontent.com/assets/222463/11122064/a84b27a2-8959-11e5-98a7-8bb430c1ef7d.png)

**Comment by HelaG** [comment]
[Premier tests enregistrés](https://github.com/sgmap/openfisca-france/commit/5693c84c6b88f81f2ea5d7b2266a105e3c434ac4#diff-84f6e941d7f566820226146e2e0be087) mais je crois que je ne maitrise pas encore la pull request :/

**Comment by MattiSG** [comment]
On affichera pour le moment une non-calculabilité avec indication de contacter la MDPH la plus proche. Cela offrira également la possibilité de créer des tests Ludwig sur la prestation.

**Comment by MattiSG** [comment]
- [ ] Indiquer une non-calculabilité.
- [ ] Renommer incapacité / invalidité.
- [ ] Ajouter information sur la source du taux d’incapacité.

**Comment by MattiSG** [comment]
@HelaG : quel logo utilise-t-on ?

**Comment by HelaG** [comment]
Caf

**Comment by fpagnoux** [comment]
En ligne sur [next](http://next.mes-aides.sgmap.fr/)
@Helag, tu peux modifier le test [ici](https://github.com/sgmap/mes-aides-ui/edit/aah/app/js/constants/droits.js#L190), en choisissant "Commit directly to the aah branch" :)

**Comment by HelaG** [comment]
Done!

**Comment by fpagnoux** [comment]
@helag, @mattisg, quel help texte pour exprimer la source du taux d'incapacité ?
La réponse administrative serait `Ce taux est déterminé par la CDAPH.`, avec un surtexte pour expliciter l'acronyme, mais c'est pas très activable pour le bénéficiaire potentiel.
 
Sinon `Ce taux pourra être évalué auprès d'une MDPH`, avec le [même lien] (http://informations.handicap.fr/carte-france-mdph.php) qu'en fin de simulation ?

**Comment by HelaG** [comment]
D'après @Flightan le taux d’incapacité est déifini par une équipe pluridisciplinaire avant le passage en CDAPH.

:+1: pour la deuxième formulation "Ce taux pourra être évalué par votre MDPH" avec le même lien.

**Comment by MattiSG** [comment]
> pour la deuxième formulation "Ce taux pourra être évalué par votre MDPH" avec le même lien.

+1

**Comment by MattiSG** [comment]
Ou même "sera".

**Comment by MattiSG** [comment]
Ou "est", si je l'ai déjà ?

**Comment by MattiSG** [comment]
> (désolé pour le spam, la prochaine fois je réfléchirais avant de poster)

**Comment by MattiSG** [comment]
En fait, dans le contexte, on n'a probablement pas besoin de rappeler "ce taux".

"Évalué par votre <abbr title="Maison Départementale des Personnes Handicapées">MDPH</abbr>" ou
"Comme évalué par votre <abbr title="Maison Départementale des Personnes Handicapées">MDPH</abbr>" ?

**Comment by fpagnoux** [comment]
Pour faire valider les tests, il faudrait mettre en prod sur next une version non-censurée. Mais next est down en ce moment...

**Comment by HelaG** [comment]
- [ ] documenter le wiki
