### ISSUE TITLE
Mettre à jour la FAQ

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#177]

**Comment by HelaG** [comment]
Remplacée par #180

**Comment by fpagnoux** [comment]
@helag, 
Dans ces cas-là, ce que tu peux faire, c'est ne pas fermer l'issue mais mettre dans ce texte dans la pull request:
`Connected to #117`
Comme ça les deux apparaîtront ensemble dans Waffle sous cette forme:
![image](https://cloud.githubusercontent.com/assets/11834997/10394469/be01355a-6e97-11e5-94f5-242f3cf1560f.png)
