### ISSUE TITLE
Pouvoir saisir des pensions alimentaires versées non multiples de 100€

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#179]
En tant que bénéficiaire potentiel versant des pensions alimentaires non multiples de 100€,
Je peux déclarer ces pensions alimentaires,
Pour les prendre en compte dans ma base ressource

- - - - -

Communication :

- [x] Mail du 28 sept. 2015 à 16:56

- - - - -

Reproduit sous :

- Edge/Win10
![Edge/Win10](https://cloud.githubusercontent.com/assets/222463/10389517/c01afb20-6e72-11e5-927b-1fc170548925.png)
- Chrome45/Win10
![Chrome45/Win10](https://cloud.githubusercontent.com/assets/222463/10390433/e4bc4956-6e78-11e5-9d06-f1b8a168eeac.png)
- Chrome45/OSX10.10
![capture d ecran 2015-10-09 a 11 27 17](https://cloud.githubusercontent.com/assets/222463/10390437/f1b3d2dc-6e78-11e5-8fbd-c57619919f7e.png)
- FF40/OSX10.10

**Comment by fpagnoux** [comment]
Bizarre, c'est pourtant le même composant que pour les ressources, et là ça ne pose pas ce problème -_-

**Comment by fpagnoux** [comment]
Reproduit sous Chrome et Firefox, ok sous Safari.

**Comment by MattiSG** [comment]
@fpagnoux `step="any"` ?

**Comment by fpagnoux** [comment]
We can  just delete the `step="100"`. It would just bring us back to a `1` increment when the user click on the arrow on the montant boxes. But I guess it's better than this bug.

**Comment by MattiSG** [comment]
It is better, but it would still give validation errors if the user sets decimal values… How do the arrows impact the value is the `step` is set to `any`?

> But I guess it's better than this bug.

Agreed.

**Comment by fpagnoux** [comment]
It increments by one, so I guess it's fine
