### ISSUE TITLE
Capturer l'AEEH

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/mes-aides-ui#191]
En tant que bénéficiaire potentiel touchant l'AEEH, je peux la déclarer dans l'écran ressoures pour qu'elles soient prises en compte pour le calcul de mes aides.

- - - - -

Communication :

- [ ] Mail du 30 octobre à 21:31

**Comment by fpagnoux** [comment]
Easy to capture in the interface, the only challenge is to now how it is taken into account into each prestation.

**Comment by fpagnoux** [comment]
The AAH is taken into account in all the prestations we calculate today.

**Comment by MattiSG** [comment]
> The AAH is taken into account in all the prestations we calculate today.

AAH ou AEEH ?

**Comment by HelaG** [comment]
L'AEEH n'est pas déclarée aux impôts (cf. [exonération](https://www.service-public.fr/particuliers/vosdroits/F3153)). Elle n'entre donc pas dans la base ressource des prestations calculées sur les revenus fiscaux n-2.

L'AEEH est exclue de la base ressource du RSA (cf. [alinéa 6 de l'art.R.262-11](http://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=?idArticle=LEGIARTI000022221917&cidTexte=LEGITEXT000006074069&dateTexte=20100714))

**Comment by HelaG** [comment]
Aucune prestation ne prend en compte l'AEEH dans sa base ressource.
Un usager a été surpris de ne pas pouvoir déclarer qu'il percevait l'AEEH.

3 possibilités :
- on garde le comportement actuel en sous-entendant que les natures de ressources qui ne peuvent pas être saisies ne sont pas prises en compte pour le calcul des prestations simulées :(
- on ajoute un champ "Autre ressource" dans lequel l'utilisateur saisi toute nature de ressources qu'il n'a pas pu saisir ailleurs - en suivant les ressources saisies dans ce champ on peut identifier d'éventuelles améliorations à apporter :/
- on capture l'AEEH et ouvre le droit au PFL pour les familles avec un seul enfant qui bénéficient de l'AEEH :)

**Comment by fpagnoux** [comment]
Ok, je pense qu'on peut capturer l'AEEH.
Par contre, si cette capture nous amène à affiner Paris Logement Famille, mieux vaut créer une autre carte :)

**Comment by MattiSG** [comment]
> je pense qu'on peut capturer l'AEEH.

C'est à déclarer comme un revenu de l'enfant ou du parent ? Ça change quelque chose ?

**Comment by MattiSG** [comment]
En fait, le mieux serait de capturer la perception (= sentiment de prise en compte pour le déclarant) sans capturer les montants (= lourd), non ?

**Comment by fpagnoux** [comment]
>C'est à déclarer comme un revenu de l'enfant ou du parent ? 
Ressource familiale, aucune importance :)
