### ISSUE TITLE
Finir sa simulation après avoir déclaré des pensions alimentaires versées

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#196]

**Comment by fpagnoux** [comment]
Pas reproduit sous chrome pour une famille avec : 
- 2 enfants
- 1 conjoint
- Locataire
- Salaire pour le demandeur

**Comment by MattiSG** [comment]
Non reproduit sous FF 40.0.3 / OS X 10.10.5.
![capture d ecran 2015-11-09 a 14 17 40](https://cloud.githubusercontent.com/assets/222463/11034549/a745b5d0-86ec-11e5-855c-d68cfb31978f.png)

**Comment by HelaG** [comment]
J'ai réussi à reproduire le bug avec [Windows 7 / Chrome 31](https://saucelabs.com/beta/tests/b463fea1ea884676b146fc06666f0163/watch).

Le bug n'est pas reproduit sur : 
- [Windows 7 / Chrome 30](https://saucelabs.com/beta/tests/bbf7983760b84dfd97f4778d914253d0/watch)
- [Windows 8 / Chrome 31](https://saucelabs.com/beta/tests/6ce6342cdd974df791862acf21669f80/watch)
- [Windows 8 / Chrome 30](https://saucelabs.com/beta/tests/fefad529e80e481cbe1e518fb7669249/watch)
- [Windows 8 / Firefox 31](https://saucelabs.com/beta/tests/8af346970afd4cedb5b7004028c6ba0a/watch)
- [Windows 8 / Firefox 23](https://saucelabs.com/beta/tests/de71a1d1e55a4ee1a6c38fc24661a6a5/watch)

**Comment by MattiSG** [comment]
Quel courage, bravo !!

Reproduit-on sur Windows 7 / Chrome 46 ?

**Comment by MattiSG** [comment]
Je ne reproduis pas sous [Ch46/Win7](https://saucelabs.com/beta/tests/d85392432f554aba9412dfdf5f0c6c38) en remplissant correctement.
En revanche, si [j'efface les montants dans le formulaire et que je valide](https://saucelabs.com/beta/tests/1eda73adc6734a63a9bcd5f6dde400c1), j'ai effectivement une erreur, comme indiqué sous [Ch31/Win7](https://saucelabs.com/beta/tests/b463fea1ea884676b146fc06666f0163/watch).

Le problème est évidemment lié au choix d'implémentation `novalidate` dans #192.

Le moyen de corriger consisterait en réimplémenter la validation native de `required`.

**Comment by MattiSG** [comment]
J'ai l'impression que le problème n'est pas de pouvoir finir sa simulation, mais de ne pas avoir d'erreur en ne remplissant pas le champ "pension alimentaire" tout en ayant déclaré en percevoir… Un problème, certes, mais peut-être pas majeur.

**Comment by HelaG** [comment]
C'est aussi en effaçant les montants renseignés en pensions alimentaires que j'arrive à reproduire avec [Windows 7 / Chrome 31](https://saucelabs.com/beta/tests/b463fea1ea884676b146fc06666f0163/watch)

**Comment by fpagnoux** [comment]
Mergé et déployé
