### ISSUE TITLE
Ajouter la prime d'activité

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#199]

**Comment by HelaG** [comment]
[Art L842 du CSS](http://www.legifrance.gouv.fr/affichCode.do?idSectionTA=LEGISCTA000031087625&cidTexte=LEGITEXT000006073189&dateTexte=20160101)

**Comment by fpagnoux** [comment]
Merge dans Openfisca pas possible pour le moment, le build est cassé

**Comment by MattiSG** [comment]
- [x] [Twitter](https://twitter.com/mesaides/status/683975891756650497)
- [x] DGCS
