### ISSUE TITLE
Valider les tests en attente sur Ludwig

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#201]
En tant que contributeur du grand public,
Je peux voir la totalité des tests créés,
Pour évaluer correctement la fiabilité de Mes Aides

- - - - - -

Il reste aujourd’hui une quarantaine de tests « En attente ». Il faut les valider ou les refuser.

**Comment by fpagnoux** [comment]
Done, il en reste une petite dizaine.
Certains qui attendent un éclaircissement, d'autres sur lequel j'ai un doute. On en parle demain.

**Comment by HelaG** [comment]
Du coups j'ai commencé à actualiser le suivi des tests rouges avec les tests récemment validés :
[Carto Tests rouges.xlsx](https://github.com/sgmap/mes-aides-ui/files/108085/Carto.Tests.rouges.xlsx)
