### ISSUE TITLE
Améliorer la capture des revenus sur 12 mois

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#22]
En tant que bénéficiaire potentiel,
Je ne fais **pas d'erreur lors de la saisie de mes revenus**,
Pour ne pas fausser l'estimation

Origine du besoin : tests utilisateurs 09/03 (75% d'échec)

**Comment by MattiSG** [comment]
- [ ] Modifier l'interface du widget.
- [ ] Préciser que les montants sont _nets_.

**Comment by MattiSG** [comment]
+1 via mail du jeudi 21 mai 2015 10:46 fwd le 21/05/15 à 11:03.

**Comment by Anne-LaureM** [comment]
Distinguer pour les demandeurs d'emploi les salaires interrompus donnant droit aux allocations chômage et les salaires issus d'une activité partielle
Pouvoir capturer pour les demandeurs d'emploi si l'interruption de leur salaire va donner lieu à un revenu de substitution

**Comment by MattiSG** [comment]
Soit le cas suivant :
- J'ai un temps partiel salarié A qui me rapporte 520€ / mois.
- J'ai un temps partiel salarié B qui me rapporte 480€ / mois.

Lorsque je fais la simulation, je viens de quitter mon travail A. Je ne toucherai donc plus de ressources de A.

Que se passe-t-il au niveau de la neutralisation des ressources dans les bases ressources ? Doit-on neutraliser toutes les ressources salariées, ou ne compter que les revenus de B ?

poke @HelaG

**Comment by HelaG** [comment]
On ne neutralise que la ressource qui n'est plus perçue, soit les revenus de A.

**Comment by HelaG** [comment]
Oui, c'est bien [ça](https://github.com/sgmap/mes-aides-ui/issues/77)

**Comment by MattiSG** [comment]
Mmh, intéressant. Merci !  :)

**Comment by MattiSG** [comment]
Les utilisateurs ne savent pas comment déclarer les ressources suivantes :

- Piges.
- Retraites complémentaires.
- Droits d'auteur.
- Cachets.

_(je copie dans le premier message pour faciliter le suivi)_

**Comment by MattiSG** [comment]
Première étape @fpagnoux :

- [ ] Rendre dépliables les catégories et les plier par défaut.
- [ ] Changer le titre "Ressources de votre foyer" en "Ressources de votre foyer depuis {{m-12}}".
- [ ] Ne pas calculer automatiquement le n-1.
- [ ] Changer "de {{m-12}} à {{m-1}}" en “Total depuis {{m-12}}".

**Comment by MattiSG** [comment]
- [ ] Explication COPIL difficultés voie rapide.
