### ISSUE TITLE
Déclarer les revenus locatifs comme ressource plutôt que comme patrimoine

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#220]
En tant que propriétaire,
Je peux déclarer des revenus locatifs,
Pour prendre en compte toutes mes ressources

---

### Communication
- [ ] Mail du 6 déc. 2015 à 17:02.

**Comment by fpagnoux** [comment]
Est-ce que ça ne vaudrait pas aussi la peine de bouger au passage les revenus du capital :thinking: ?

**Comment by fpagnoux** [comment]
![image](https://cloud.githubusercontent.com/assets/11834997/19690096/cbd35978-9acf-11e6-90c4-88d322c3aee1.png)

**Comment by MattiSG** [comment]
:+1:

Il faudra probablement une nouvelle catégorie de ressources, du coup, mais c’est une super idée pour traiter petit à petit le boulot de la page Patrimoine !
