### ISSUE TITLE
Ne pas proposer la CMU ni le RSA en cas d'AAH

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#221]
En tant que bénéficiaire de l’AAH,
On ne me propose pas d’aide incompatible avec cette aide,
Pour ne pas surestimer mes droits

**Comment by fpagnoux** [comment]
L'AAH n'étant pas calculée par mes-aides, il paraît difficile de prendre en compte les interactions avec une prestation que l'on percevra "peut-être".
Solutions possibles :
- Investir dans des commentaires dépendant de la situation ("Vous ne percevrez  pas cette prestation si vous bénéficiez de l'AAH"). Pas sûr qu'on ait le temps.
- Ne pas calculer ni afficher l'AAH. Ce ne rendra pas le résultat plus juste (une personne qui peut avoir de l'AAH se vera proposer du RSA) mais au moins pas d'incompatibilité flagrante sur la page de résultat.

**Comment by MattiSG** [comment]
> Investir dans des commentaires dépendant de la situation ("Vous ne percevrez pas cette prestation si vous bénéficiez de l'AAH"). Pas sûr qu'on ait le temps.

Pour moi, avant même la question des ressources, c'est surtout une question d'expérience utilisateur. La promesse est d'estimer le droit à des prestations. Si on arrive à un résultat où _tout_ est conditionné à une évaluation externe, franchement, je ne vois pas à quoi Mes Aides sert. Autant dire dès le début qu'on ne prend pas en charge ces situations, comme pour Mayotte, plutôt que de faire remplir plein d'infos pour dire à la fin « on sait pas »  😒

**Comment by MattiSG** [comment]
Après discussion en COPIL : la situation actuelle est pertinente, notamment au vu des délais d'instruction de l'AAH. La simulation aboutit à un résultat « en l'attente d'attribution d'une AAH », et quand elle est perçue, elle est déclarée et non recalculée.
