### ISSUE TITLE
Impossible de télécharger le formulaire de demande RSA

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#238]
Depuis sgmap/openfisca-france#47 :

> Url: https://mes-aides.gouv.fr/telecharger-formulaires/rsa
> Après simulation des aides, lors de la dernière étape, lorsque je veux télécharger le formulaire de demande, l'API me retourne une erreur:
> 
```
Oops, an error occured
This exception has been logged with id 6ondon1lf.
```

- [ ] Essayer de reproduire deux fois d'affilée (avec le fournisseur de service externe "chaud").

**Comment by fpagnoux** [comment]
Cerfa generator has been deprecated.
