### ISSUE TITLE
Mettre à jour la base de donnée des codes postaux

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#25]
En tant que bénéficiaire potentiel,
Je peux sélectionner ma commune à partir de son code postal,
Pour déterminer mon éligibilité aux prestations territorialisées

Origine du besoin : retour utilisateur (ville non chargée)

- [x] Mettre à jour la base de données de codes postaux vers [la base sur data.gouv.fr](Le fichier CP
https://www.data.gouv.fr/_uploads/resources/communes-plus-20140630-csv.zip).
- [x] Publier un module NPM `codes-postaux` qui embarque la base et fournit une API minimale.

**Comment by MattiSG** [comment]
Après discussion IRL : utiliser une base et un service locaux, pour ne pas avoir de dépendance sur un service externe pour un élément sur le chemin critique de l'usager. Aujourd'hui, si le service tombe, toute l'application est inaccessible.

Ce choix d'implémentation aura aussi pour effets de bords positifs de :
- Faciliter le développement en local et en offline.
- Distribuer un paquet facilitant la réutilisation des données ouvertes françaises.

**Comment by MattiSG** [comment]
+1 via mail du jeudi 21 mai 2015 10:46 fwd le 21/05/15 à 11:03.

**Comment by MattiSG** [comment]
https://github.com/sgmap/codes-postaux :dancer:

**Comment by HelaG** [comment]
Le mail à la "contributrice" de jeudi 21/05 a été envoyé. Done?

**Comment by MattiSG** [comment]
@HelaG Carrément, je voulais vérifier avec vous cet après-midi mais pour moi c'est done.
