### ISSUE TITLE
Sortir un enfant du foyer quand ses ressources baissent le RSA du foyer

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#258]
Calcul comparatif d'un RSA avec prise en compte de l'enfant et d'un RSA sans l'enfant à charge. 
Le foyer a droit au RSA le plus "avantageux".

**Comment by HelaG** [comment]
@marion-DGCS

**Comment by fpagnoux** [comment]
Test associé: http://localhost:9000/tests/546caea677dfcb2a7d6cedfb/show

**Comment by fpagnoux** [comment]
Test passé au vert.
