### ISSUE TITLE
Ne plus afficher l'hypothèse de stabilité des revenus quand les revenus N-2 ont été déclarés

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#263]
Entant que bénéficiaire potentiel aux aides au logement, 
A la fin de ma simulation, après avoir déclaré des revenus N-2 égals à 0, 
Je ne vois plus l'hypothèse de stabilité des ressources entre les 12 derniers mois et le N-2 apparaitre.

- [ ] Retour utilisateur Fb

**Comment by HelaG** [comment]
Il s'agit d'une régression du comportement sur la UI. 
Corriger cette issue = Refaire la même chose

Quels types de tests pourraient-on mettre en place pour éviter ça ?

**Comment by MattiSG** [comment]
Il nous faut le navigateur dans lequel le problème est apparu, car je n'arrive pas à reproduire.

> Quels types de tests pourraient-on mettre en place pour éviter ça ?

[Tests d'intégration](https://speakerdeck.com/mattisg/state-of-web-integration-testing).

**Comment by HelaG** [comment]
Je reproduit le bug sur Firefox 38.0 - l'utilisateur à l'origine de ce retour était sur Chrome. 

J'ai précisé l'issue, c'est quand le montant des revenus N-2 est égal à 0 que le message s'affiche toujours.

**Comment by fpagnoux** [comment]
Epic fail de notre (ma) part, vu le temps qu'on a passé là-dessus on devrait pas avoir ce genre de bugs...
Tant qu'on est sur cette version de mes-aides, la seule alternative aux TI serait de systématiquement déployer une instance spécifique pour faire tester par @HelaG  (au moins sur le périmètre de la PR).

**Comment by MattiSG** [comment]
Ben, ça reste un test d'intégration… mais manuel au lieu d'automatique  :wink:
