### ISSUE TITLE
Prendre en compte l'AAH dans la base ressources de la Prime d'activité.

### ISSUE THREAD

**Issue by marion-DGCS** [sgmap/mes-aides-ui#270]
https://mes-aides.gouv.fr/acceptance-tests/5714c704223ed8d264bc60e6/show?keyword=prime%20d%27activit%C3%A9

**Comment by fpagnoux** [comment]
Merci @marion-DGCS pour la création de ce test.
Nous ne connaissons pas les détails spécifique de la prise en compte de l'AAH dans la base ressource de la Prime d'activité. Est-ce que tu peux nous les indiquer ici - et éventuellement la référence legislative - s'il te plaît ?
Merci !

**Comment by marion-DGCS** [comment]
L'AAH est assimilée à un revenu d'activité lorsque son bénéficiaire à un revenu d'activité (hors AAH, bien sûr) supérieur ou égal à 29 fois le SMIC horaire brut, soit 280,43 € au 1er janvier 2016.
Assimilée à un revenu d'activité, l'AAH est alors prise en compte à 38%, et ouvre droit à la bonification.
Attention : c'est le bénéficiaire de l'AAH qui doit individuellement remplir cette condition, et non une autre personne du foyer.

________________________________

De : Florian Pagnoux [mailto:notifications@github.com] 
Envoyé : lundi 18 avril 2016 17:45
À : sgmap/mes-aides-ui
Cc : TONNES, Marion
Objet : Re: [sgmap/mes-aides-ui] Test 16_BAAH_EligiblePrime Prime d'activité (#270)



Merci @marion-DGCS <https://github.com/marion-DGCS>  pour la création de ce test.
Nous ne connaissons pas les détails spécifique de la prise en compte de l'AAH dans la base ressource de la Prime d'activité. Est-ce que tu peux nous les indiquer ici - et éventuellement la référence legislative - s'il te plaît ?
Merci !

**Comment by fpagnoux** [comment]
Merci Marion pour ces précisions très utiles, nous allons implémenter cette règle spécifique à l'AAH.
J'ai une question sur le cas de test que tu cites.
Si je comprends bien, l'AAH est considéré comme un revenu d'activité. 
Donc `revenu d'activité total = 800 + 281 = 1081€`
Or `montant forfaitaire familial pour une personne seule sans FL = 524€`
J'ai bien `524 - 0.38 * 1081 = 113€`, le résultat que tu indiques dans le test.
Mais ne faut-il pas y ajouter une bonification ? Car avec un revenu d'activité de 1081€, on a normalement la bonification maximale de 67€, non ?
Est-juste un oubli, où est-ce que l'AAH ne doit pas être pris en compte dans la bonification ?

**Comment by marion-DGCS** [comment]
Effectivement, il s'agit d'une erreur de ma part : dès lors que l'AAH est assimilée à un revenu d'activité, elle ouvre droit à la bonification.
 
Marion

________________________________

De : Florian Pagnoux [mailto:notifications@github.com] 
Envoyé : mardi 3 mai 2016 18:55
À : sgmap/mes-aides-ui
Cc : TONNES, Marion; Mention
Objet : Re: [sgmap/mes-aides-ui] Prendre en compte l'AAH dans la base ressources de la Prime d'activité. (#270)



Merci Marion pour ces précisions très utiles, nous allons implémenter cette règle spécifique à l'AAH.
J'ai une question sur le cas de test que tu cites.
Si je comprends bien, l'AAH est considéré comme un revenu d'activité. 
Donc revenu d'activité total = 800 + 281 = 1081€
Or montant forfaitaire familial pour une personne seule sans FL = 524€
J'ai bien 524 - 0.38 * 1081 = 113€, le résultat que tu indiques dans le test.
Mais ne faut-il pas y ajouter une bonification ? Car avec un revenu d'activité de 1081€, on a normalement la bonification maximale de 67€, non ?
Est-juste un oubli, où est-ce que l'AAH ne doit pas être pris en compte dans la bonification ?

**Comment by fpagnoux** [comment]
Règle implémentée, test passé au vert. Merci Marion.
