### ISSUE TITLE
Indiquer que le montant des aides locales n'est pas pris en compte dans le calcul des aides nationales

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/mes-aides-ui#273]
En tant que bénéficiaire potentiel à qui l'on annonce que je peux percevoir des aides locales et des aides nationales,
On m'indique que l'impact des premières n'est pas pris en compte sur les dernières,
Pour que je ne surestime pas les aides que je peux percevoir.

**Comment by fpagnoux** [comment]
Proposition 1
-----------------

![image](https://cloud.githubusercontent.com/assets/11834997/14711249/e985ad66-07d8-11e6-95b2-40dc3792e19b.png)

**Comment by fpagnoux** [comment]
Proposition 2
-----------------
![image](https://cloud.githubusercontent.com/assets/11834997/14711364/5c84d35a-07d9-11e6-8a05-d37bedd7f8b4.png)

Risque: le "Déclarez vos ressources 2013" est un peu plus loin, donc moins visible ?

**Comment by fpagnoux** [comment]
@MattiSG ?

**Comment by MattiSG** [comment]
Et avec les aides locales dans un autre bloc ?

Pour le positionnement du CTA ressources n-2, je le laisserais bien sous les aides nationales (en fait, sous le bloc d'aides qui pourrait en dépendre). Tout en haut, ça m'ennuie car d'une part ça le met vraiment beaucoup en avant, et d'autre part on a des tests utilisateur qui valident le positionnement actuel et pas d'idée de l'impact de remonter…

Pour la formulation, j'enlèverais le "attention" (surtout qu'il n'est pas raccord avec le picto "info"). On itèrera dans tous les cas sur la phrase, mais c'est un bon début.

**Comment by fpagnoux** [comment]
Proposition 3
-----------------
![image](https://cloud.githubusercontent.com/assets/11834997/14712090/1d1c67e8-07dc-11e6-8db6-9d3e249a58e6.png)

**Comment by fpagnoux** [comment]
Proposition 4
-----------------

![image](https://cloud.githubusercontent.com/assets/11834997/14712138/4f7ce334-07dc-11e6-94ff-b58fc518556b.png)

**Comment by fpagnoux** [comment]
Proposition 4.1
--------------------
![image](https://cloud.githubusercontent.com/assets/11834997/14712222/8fbd240e-07dc-11e6-9e99-c8bbd557bafb.png)
(Deux textes d'introduction cohérents)

**Comment by MattiSG** [comment]
Je penche clairement pour 4.1, en uniformisant l'intro du premier bloc pour parler d'aides « nationales ». Je mettrais bien l'info sur le changement de montant en bas du bloc, comme pour les ressources n - 2.

**Comment by fpagnoux** [comment]
![image](https://cloud.githubusercontent.com/assets/11834997/14790219/94e734ba-0b10-11e6-82c9-aa1736ba51c2.png)

**Comment by fpagnoux** [comment]
Est-ce qu'on veut garder le
> D'après la situation que vous avez décrite, vous êtes **a priori**

?

**Comment by MattiSG** [comment]
Ça sautera quand on enlèvera le bandeau beta, non ?
