### ISSUE TITLE
Base ressources RSA

### ISSUE THREAD

**Issue by marion-DGCS** [sgmap/mes-aides-ui#277]
Les ressources à prendre en compte dans la base RSA doivent être vérifiées conformément au test qui a été rejeté.
https://mes-aides.gouv.fr/tests/57208c76a1cf53ce641d4a80/show
Il est ici question de la prime forfaitaire mensuelle ASS, mais toutes les ressources testées dans : https://mes-aides.gouv.fr/acceptance-tests/54817f52ed60b88866befc05/show?keyword=rsa&state=rejected&state=validated&state=pending doivent être intégrées à la base ressources RSA

**Comment by fpagnoux** [comment]
Il a bien été vérifié que toutes les ressources étaient prises en compte dans la BR du RSA.
