### ISSUE TITLE
Rendre accessibles les boutons de type de logement

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#293]
En tant que déficient visuel,
Je peux avoir un retour vocal standard sur mon type de logement,
Pour le décrire correctement

**Comment by MattiSG** [comment]
A priori, boutons radio.

**Comment by fpagnoux** [comment]
Documentation about radio buttons accessibility:
- http://www.coolfields.co.uk/2011/04/accessible-forms-checkboxes-and-radio-buttons/

**Comment by MattiSG** [comment]
Communication DGCS faite.
