### ISSUE TITLE
Déclarer des revenus en tant qu'apprenti

### ISSUE THREAD

**Issue by Astaoth** [sgmap/mes-aides-ui#3]
Bonjour,

Lorsqu'on est étudiant, on devrait pouvoir indiquer également une situation de salarié (étudiant salarié, apprenti, etc) ce qui n'est pas possible actuellement.

NB : pour l'année 2013, un apprenti n'est imposable qu'avec un revenu supérieur à 1430€ mensuel. Si son salaire est inférieur, son revenu imposable est de 0€. Si son revenu est supérieur (par exemple 1500€ mensuel), alors son revenu imposable n'est que la différence entre son salaire et le seuil d'imposition (dans notre exemple, le salaire imposable est de 1500-1430 = 70€).

**Comment by MattiSG** [comment]
Le problème n'est plus remonté depuis les améliorations UX de l'été 2015.
