### ISSUE TITLE
Ajouter la Majoration pour vie autonome comme ressources à déclarer

### ISSUE THREAD

**Issue by HelaG** [sgmap/mes-aides-ui#327]
## Communication
- [ ] Répondre à l'usager qui nous a contacté à ce sujet le Jul 25, 2016 at 11:01 PM
- [ ] Rennes Métropole (exclu de la BR Transport)

**Comment by MattiSG** [comment]
Important de séparer, certaines prestations (exemple : Rennes Métropole Transport) ne prennent en compte que l'AAH et excluent la MVA de leur base ressource.
