### ISSUE TITLE
Capturer l'échelon de bourse pour les étudiants

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#336]
En tant qu'étudiant boursier résidant à Rennes Métropole,
Je peux indiquer mon échelon de bourse,
Pour déterminer mon éligibilité au Tarif solidarité transport

---

Il faut demander pour l'année universitaire n-1 / n jusqu'en juin (à vérifier, selon les retours des DSE), n / n+1 ensuite.

---

Possibilités :
1. Remplacer le oui / non pour les étudiants boursiers par un sélecteur d'échelon.
2. Poser la question si CP dans Rennes Métropole.
   …

**Comment by fpagnoux** [comment]
- [ ] Pré-remplir le montant de la bourse (Essayer de se baser sur l'api openfisca (`/parameters`)
- [ ] Remplacer Oui/Non par un `<range>`
