### ISSUE TITLE
Prendre en charge les auto-entrepreneurs

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#35]
En tant qu'auto-entrepreneur,
Je peux comparer mon chiffre d'affaire au maximum autorisé,
Pour déterminer mon éligibilité au RSA

**Capture** :
- [ ] trois derniers mois (pas trimestre, trois derniers mois !)
- [ ] type d'activité (BIC/BNC/achat-revente). Permet de déterminer les plafonds.

**Interface** : 
- [ ] éclater micro-entreprise/AE dans l'écran de capture des ressources.

**Incertitude** : si les plafonds sont trimestriels et non annuels, et que les plafonds d'éligibilité RSA sont > aux plafonds AE, alors pas besoin de capturer le CA année précédente, puisque le statut d'AE donne immédiatement l'éligibilité RSA.

**Comment by fpagnoux** [comment]
Point soulevé par @jdesboeufs : 
Si on implémente avec ces abattements, cela revient à considérer que pour les auto-entrepreneurs on prend en compte le revenu brut pour l'attribution du RSA, alors que dans tous les autres cas on prend le net. 
En attente de validation par Hela auprès des caisses

**Comment by fpagnoux** [comment]
A voir avec Hela : 
- Faire valider le calcul précis pour un test 
- Les revenus AE doivent-ils être neutralisables ? 
- Dans quels cas doit-on demander s'il y a des employés ?
