### ISSUE TITLE
Revalorisation au 01/09

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#372]
> Le Revenu de solidarité active (RSA) "sera à nouveau revalorisé de 2% en septembre prochain, comme chaque année depuis 2013"

http://www.europe1.fr/economie/le-rsa-augmentera-de-2-au-mois-de-septembre-2719870

**Comment by fpagnoux** [comment]
See  https://github.com/openfisca/openfisca-france/pull/579
