### ISSUE TITLE
Dégressivité

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#377]
https://www.caf.fr/ma-caf/caf-de-la-haute-savoie/partenaires/aides-au-logement-nouveau-calcul-a-compter-de-juillet-2016

Cf. openfisca/openfisca-france#546

**Comment by monbocal** [comment]
Apparement, https://github.com/openfisca/openfisca-france/pull/651 s'en charge déjà. Nous avons reçu un mail le 05/04/17 nous demandant de l'intégrer. @fpagnoux peux tu confirmer ? Merci.

**Comment by MattiSG** [comment]
@fpagnoux J'imagine que cela dépend de #519 ?

**Comment by fpagnoux** [comment]
Oui, exactement.
