### ISSUE TITLE
Indiquer quand une mise à jour a lieu

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#391]
En tant que personne effectuant une simulation,
Je suis informé d'une mise à jour de l'application,
Pour ne pas croire qu'il y a un bug alors qu'il suffit de réessayer quelques secondes plus tard

---

Le déploiement continu donne lieu à des indisponibilités d'une trentaine de secondes pouvant apparaître en journée. Au vu de la multiplication des usages, cela mène à des simulations faisant croire à un bug.
## Source
- Mail du 17/10/2016 à 11h56.

**Comment by MattiSG** [comment]
Il suffit peut-être simplement de modifier le wording du message d'erreur ? On a très peu de véritables erreurs aujourd'hui.

**Comment by fpagnoux** [comment]
- [ ] Indiquer qu'il s'agit probablement une mise à jour
- [ ] Indiquer à l'utilisateur qu'il peut recharger la page dans quelques minutes pour obtenir ses résultats
- [ ] Timer pour actualiser ?

**Comment by fpagnoux** [comment]
J'ai fait des tests pour voir comment se comporte la page de résultats lors d'un déploiement.

Pendant 10 secondes, le site est HS, mais il n'y a pas de message d'erreur, puisque même angular ne fonctionne pas.  L'incident reporté par le mail mentionné était bien réel, puisque des versions incompatibles de mes-aides et openfisca se sont retrouvés en prod simultanément pendant 10 minutes.

Je pense qu'on peut donc continuer à inciter les utilisateurs à nous contacter lorsqu'ils voient la pop-in, car, jusqu'à preuve du contraire, elle ne s'affiche qu'en cas de réel bug.

Par contre, je ne sais pas comment on pourrait traiter les 10 secondes où le site est down, ni si c'est quelque chose à prioriser.

**Comment by MattiSG** [comment]
Ok, si c'est très court et que l'application n'est de toute façon pas en état d'afficher quoi que ce soit, attendons.
