### ISSUE TITLE
Restaurer l'accès après les pensions alimentaires versées

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#393]
Il y a apparemment un problème bloquant l'accès aux résultats de la simulation, on a reçu deux signalements en très peu de temps : 

- [ ] Mail du 26 octobre 2016 08:29:40 UTC+2
- [ ] Mail du 26 octobre 2016 08:26:12 UTC+2

Je ne reproduis pas avec Safari 10.
L'un a lieu avec Windows Phone 10, l'autre n'est pas encore identifié.

**Comment by MattiSG** [comment]
Je n'ai pas de Windows Phone accessible via SauceLabs.

Je ne [reproduis pas](https://saucelabs.com/beta/manual/test_proxy/83eb46f7581d4f1a995f3297bae8e01b) sur IE11 / Windows 10.

**Comment by MattiSG** [comment]
Reproductible par l'utilisateur sous FF46.
Je ne reproduis pas sous FF48.

C'est certainement une incompatibilité avec des éléments de la situation que je ne connais pas.
Je vais tenter de faire une simulation plus complète.

**Comment by fpagnoux** [comment]
S’ils les utilisateurs ont écrit à bug@mes-aides.gouv.fr, c’est que la modale s’est affichée

**Comment by fpagnoux** [comment]
Reproduit en local en déclarant tout.

**Comment by fpagnoux** [comment]
La version installée de `mes-aides-api` semble être 3.2.0, pas compatible avec `mes-aides-ui/master` depuis `clean-api`. Je ne comprends pas pourquoi cette version est installée plutôt que 4.0.0.

**Comment by fpagnoux** [comment]
Got it, le tag `v4.0.0` n'a pas été publié sur le bon commit  ☹️ 🔫

**Comment by fpagnoux** [comment]
Résolu.
On aurait pu éviter ce problème avec au choix: 
    - Des tests d'intégration qui tournent pour de vrai dans travis, en passant par les "situations particulières" type handicap, inapte au travail.
    - Un process de publication des tags automatique (similaire à openfisca)

**Comment by MattiSG** [comment]
À mon avis mieux vaudrait investir dans les tests d'intégration que dans la publication des tags, car les tests d'inté couvrent bien d'autres situations, et qu'on a plutôt à terme l'ambition de réunir API et UI dans un seul dépôt, et donc d'abandonner le processus de tags.

D'ailleurs, une autre solution pourrait être de ne plus séparer les deux…
