### ISSUE TITLE
Évaluer les droits des primo-accédants

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#419]
En tant que bénéficiaire potentiel primo-accédant à la propriété,
Je peux évaluer mes droits aux aides au logement directement dans Mes Aides,
Pour ne pas avoir à refaire ma simulation sur le site de la CAF.

- - - - 

Source : test utilisateur du 15/12/2017.

**Comment by monbocal** [comment]
+1 mail du 20/03/2017 à 23:08 & suivants

**Comment by monbocal** [comment]
+1, message reçu de la part d'un travailleur de la Carsat par rapport au fait de devoir passer sur le site de la Caf pour faire une simulation aide au logement pour un primo accédant
>Introduire cette simulation CAF dans votre application car ça facilite le travail

**Comment by guillett** [comment]
@monbocal le calcul des AL pour les primo accédants a été mis en ligne hier. C'est une opportunité pour contacter le travailleur mentionné précédemment. De plus, il faudrait voir avoir ce travailleur si il est en capacité de créer des tests lorsque les montants indiqués sont finalement différents des montants effectivement perçus. Qu'en penses-tu ?
