### ISSUE TITLE
Indiquer que la page « vos ressources » ne concernent que celles du déclarant

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#429]
En tant que déclarant ayant un conjoint,
Je suis informé que seules mes ressources personnelles sont à déclarer sur la page « Vos ressources »,
Pour ne pas avoir à les modifier en découvrant la page « Les ressources de votre conjoint ».

- - - -

Source
-------

- Mail du 4 janvier 2017 à 19:43:08

**Comment by monbocal** [comment]
Solution possible : 
* sur la page `\mes-aides-ui\app\views\partials\foyer\ressources\types` ,
* faire un **if** _conjoint déclaré_ **alors** _afficher_ "Vous pourrez déclarer les ressources de votre conjoint dans les pages suivantes, n'indiquez que vos ressources personnelles".
* et vu que cette page est réutilisée dans le cas d'un conjoint, mettre un **if** _on est sur la page du conjoint_ **alors** _on ne l'affiche pas_

J'ai expliqué ça avec des if, mais en HTML, c'est très compliqué de faire ça :) Je ne connais pas assez angular pour savoir si on peut faire une fonction avec ça ? Avez-vous d'autres pistes de résolution ?

**Comment by MattiSG** [comment]
On peut faire des `if` simplement avec Angular, reste à savoir comment est exposée la situation… Mais finalement, quel est le problème à indiquer “Vos ressources personnelles uniquement” même quand on n'a pas déclaré de conjoint ? 🙂

**Comment by guillett** [comment]
@monbocal comme discuté je te laisse essayer d'implémenter la suggestion.

**Comment by guillett** [comment]
Mis en production via #667
