### ISSUE TITLE
Reporter l'id de la simulation lorsqu'un utilisateur signale un écart de résultat.

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/mes-aides-ui#437]
En tant qu'utilisateur qui souhaite signaler un écart de résultat,
Je peux joindre à mon mail un identifiant de simulation,
Pour que l'équipe mes aides puisse analyser rapidement ma situation.

**Comment by MattiSG** [comment]
Fixed via https://github.com/sgmap/mes-aides-ui/pull/443
