### ISSUE TITLE
Gérer la résidence à l'étranger

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#439]
En tant que bénéficiaire potentiel résidant à l'étranger,
Je n'ai pas à saisir mon code postal,
Pour pouvoir finaliser ma simulation

- - - - -

Il faut également inclure la prise en charge des règles spécifiques dans ce cas, ou au moins mettre en avant les conditions de résidence.

Communication
-----------

Mail du 19 janvier 2017 à 19:25:56.

**Comment by monbocal** [comment]
+1 Mail du 21/02/17 10:26 et conversations associées

**Comment by fpagnoux** [comment]
Il est très probable qu'aucune aide calculée par mes-aides ne soit accessible aux résidents à l'étranger.

Si c'est bien le cas, peut-être faudrait-il une question en tout début de parcours ?

**Comment by MattiSG** [comment]
Duplicate of #122.
