### ISSUE TITLE
Age lors de la création d'un test

### ISSUE THREAD

**Issue by stephanecolson** [sgmap/mes-aides-ui#44]
Bonjour,

tous les âges sont minorés d'un an dans le récapitulatif "Modification du cas de test: " à l'issue du processus d'https://mes-aides.gouv.fr/tests/

**Comment by stephanecolson** [comment]
Arg j'aurais peut-être dû créer ce ticket dans ludwig-ui.  non ?

**Comment by MattiSG** [comment]
@stephanecolson Je ne pense pas, car le problème provient du [récapitulatif](https://github.com/sgmap/mes-aides-ui/blob/master/app/views/partials/recap-situation.html), et il est bien présenté par `mes-aide-ui` :)
Ludwig n'a aucune capacité de présentation des situations qu'il traite, il se contente [d'afficher]((https://github.com/sgmap/ludwig-ui#test-template) un [template](https://github.com/sgmap/mes-aides-ui/blob/master/ludwig/scenarioTemplate.js) donné par [configuration](https://github.com/sgmap/mes-aides-ui/blob/master/ludwig/config.json#L4)  :)

**Comment by MattiSG** [comment]
Peut-être corrigé par #49. Dans tous les cas, saisir l'opportunité de #49 pour définir cette issue.

**Comment by MattiSG** [comment]
@stephanecolson Pourrais-tu stp donner un lien direct vers un cas de test avec la valeur présentée et la valeur attendue ? On a un cas de non-reproduction.

**Comment by stephanecolson** [comment]
https://mes-aides.gouv.fr/tests/553695fc5a5c6d762da9ba5a/show
Né(e) le 20/08/1975 - 38 ans affichés au lieu de 39
Né(e) le 12/06/1977 - 37 ans affichés au lieu de 38 (bientôt 39)

**Comment by MattiSG** [comment]
Confirmé, je m'étais planté dans le calcul pour un enfant en bas âge  :sweat:  Merci @stephanecolson !

**Comment by MattiSG** [comment]
Woohoo, already fixed in #49 :dancer:
