### ISSUE TITLE
Valider le code postal

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#451]
En tant que bénéficiaire potentiel,
Je peux me tromper dans mon code postal
Et le système me demande de le corriger.

# Communication

Mail du 29/01/17, 15:00:28
Mail du 01/02/17, 10:08:24

**Comment by MattiSG** [comment]
La validation du code postal est en place, mais l'envoi du formulaire n'est apparemment plus bloqué. Il s'agit d'une régression.
