### ISSUE TITLE
Préciser la nationalité du conjoint

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#461]
En tant que bénéficiaire potentiel,
Je souhaite entrer la nationalité de mon partenaire / conjoint,
Pour calculer mes aides en fonction de ma situation réelle plutôt qu'en supposant que mon partenaire / conjoint est français.

**Comment by monbocal** [comment]
Suite au mail reçu le 08/02/17 15:07, effectivement, la nationalité du conjoint peut modifier certaines règles d'attribution d'aides. Exemple avec le RSA : https://www.service-public.fr/particuliers/vosdroits/F24615 .

A voir si cela impacte au cœur ou à la marge les prestations ? Dans le cas du RSA, cela a un impact en cas de carte de séjour inférieure à 5 ans.

**Comment by monbocal** [comment]
+1 mail du 18/02/17 16:12

**Comment by guillett** [comment]
Compris dans #497.
