### ISSUE TITLE
Accéder au téléservice du RSA

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#462]
En tant que bénéficiaire potentiel du RSA,
Je souhaite avoir accès directement au service en ligne de demande du RSA,
Pour ne pas avoir à imprimer et remplir le formulaire.

-- -- -- --

Depuis le 1er janvier, on peut faire sa demande de RSA directement en ligne sur le site de la CAF. Ce serait judicieux de soit remplacer le bouton "Accéder au formulaire", soit si l'interface le permet, de rajouter un bouton "Demander en ligne".

**Comment by MattiSG** [comment]
@monbocal normalement tu dois pouvoir le faire tout seul en modifiant `droits.js`, si ça te dit d’essayer on peut t’aider  :)

**Comment by monbocal** [comment]
J'ai été plus rapide que dans la pratique : ça vient de sortir pour la MSA la demande en ligne, pour les Caf, ce n'est pas encore le cas.

**Comment by guillett** [comment]
Je te laisse clôturer l'issue.

**Comment by monbocal** [comment]
Vu qu'on personnalise les liens pour les départements... On peut clore l'issue.
