### ISSUE TITLE
Préciser Net Fiscal sur la page des ressources

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#465]
En tant que bénéficiaire d'une aide potentielle,
Je souhaite dissiper le doute sur la mention "ressources nettes" sur la page de déclaration des ressources
Afin de remplir les "ressources nettes fiscales (nettes imposables)"

--

Mail du 09/02/17 12:53

**Comment by monbocal** [comment]
+1 mail du 20/03/2017 à 11:53

**Comment by fpagnoux** [comment]
Aujourd'hui, on capture le net versé, et on recalcule le net imposable (un peu plus élevé) derrière. Qu'est-ce qui nous fait pensé qu'il faudrait passer au net fiscal ?

**Comment by monbocal** [comment]
Beaucoup d'incompréhensions d'utilisateurs sur cette page face à la mention "ressources nettes". C'est même bloquant pour certains : ce n'est pas le montant brut à renseigner, mais quel est le montant net à mettre, celui que j'ai reçu ou celui que je déclare ? Que l'on capture le net fiscal ou le net imposable, le préciser sur la page pour permettre une navigation plus fluide.

**Comment by monbocal** [comment]
Je permets d'upper avec une réflexion que je viens d'avoir : à partir de 2018, le net versé baissera mécaniquement avec le prélèvement à la source. Du coup, je pense que demander le net imposable serait plus simple : sinon, il faudrait demander le net versé avec le taux de prélèvement pour recalculer le net versé sans le prélèvement pour estimer ensuite le net imposable. Sans compter que si on ne demande pas le taux de prélèvement, il y aura forcément une différence entre deux personnes selon qu'elles aient opté pour le taux neutre ou le taux calculé.

**Comment by monbocal** [comment]
**Sauf erreur de ma part**, le seul fichier à modifier est `\app\views\partials\foyer\ressources\montants` . Il s'agit d'un texte en dur que je peux modifier en `ressources nettes versées` (ce qu'on capture actuellement).

Est ce que j'ai un OK pour faire cette PR et ainsi éviter quelques mails supplémentaire ?

**Comment by MattiSG** [comment]
Tu as une autorisation permanente d’ouvrir des PR  :)

**Comment by guillett** [comment]
Done by #558.
