### ISSUE TITLE
Préciser où regarder pour déclarer ses revenus n-1

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#480]
Sur la page de déclaration des ressources de l'année précédente en fin de simulation, il est demandé :

"Les revenus imposables de votre foyer en 2015
Ces informations se trouvent sur votre déclaration de revenus d'impôts 2015. 
Vous pouvez la retrouver en ligne sur impots.gouv.fr."

Cependant, l'usage en France est plutôt de se baser pour toutes les démarches administratives sur l'avis d'imposition, décalé d'une année.

Ainsi, si la déclaration de revenus d'impôts 2015 contient bien les revenus d'impôts 2015, c'est l'avis 2016 qui contient ceux de 2015. L'avis 2015 contient ceux de 2014.

Faut-il ajouter un éclaircissement quelconque sur cette page, les deux documents sont-ils interchangeables par rapport à dont nous avons besoin ? Une solution serait de mettre :
"Ces informations se trouvent sur votre déclaration de revenus d'impôts 2015 et sur votre avis d'impôts 2016 sur les revenus 2015".

Cette réflexion fait suite au mail reçu le 02/03/17 à 00:05

**Comment by monbocal** [comment]
+1

**Comment by monbocal** [comment]
CF https://github.com/sgmap/mes-aides-ui/pull/608

**Comment by guillett** [comment]
Closed by #608
