### ISSUE TITLE
Déclarer des frais réels déductibles avec une valeur décimale

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#485]
En tant que bénéficiaire potentiel,
Je souhaite entrer une valeur décimale dans la case "Frais réels déductibles" de n-2
Sans que la simulation ne crashe

--

Soulevé par le mail du 05/03/17 16:15 et suivants

Sur la page de déclaration des revenus imposables de l'année n-2 (accessible en fin de simulation), lorsqu'on entre un nombre à virgule dans la case "Frais réels déductibles", la simulation plante, affiche la page de bug et annonce en informations techniques "Internal Server Error" sans aucun autre détail. Testé avec les autres cases, pas de soucis : seule celle là est concernée.

**Comment by guillett** [comment]
Fixed by #637
