### ISSUE TITLE
Permettre de saisir une date sous terminal mobile

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#494]
_Cette issue peut être mise en lien avec [#343](https://github.com/sgmap/mes-aides-ui/issues/343) et je me demande même si [ceci](https://github.com/sgmap/mes-aides-ui/pull/347) n'en serait pas la cause_

En tant que bénéficiaire potentiel d'une aide,
Je souhaite pouvoir entrer une date sous terminal mobile sans avoir à déplacer mon curseur,
Afin de ne pas me tromper dans la date.

Il s'agit d'un bug que j'ai réussi à reproduire sur Android 6 / Chrome 56. En entrant une date, le curseur se décale à la mauvaise place. Avec la séquence 123456 par exemple, le comportement obtenu est celui là (le pipe est remplacé par un *) :
```
JJ/MM/AA
*JJ/MM/AA
1*
12*/
12/*03/
12/0*4/3
12/05*/43
12/05/*643

```
Avec la séquence 121212 (je vous vois venir, 34 n'est pas un mois valable)
```
JJ/MM/AA
*JJ/MM/AA
1*
12*/
12/*1
12/0*2/
12/01*/2
12/01/*22

```
--

Mail du 10/03/17 14:32, repéré sous Android avec Chrome également

**Comment by guillett** [comment]
@monbocal pourrais-tu essayer à nouveau sur la production ? J'ai essayé depuis un iPhone sur Chrome et je n'ai pas eu le problème.

Merci !

**Comment by monbocal** [comment]
Ca s'est amélioré mais j'ai maintenant des problèmes quand je veux corriger la date, le curseur repart en vrille.

**Comment by guillett** [comment]
Effectivement, j'ai un problème aussi à la modification mais seulement quand je déplace le curseur en milieu de saisie. Je n'ai pas de problème lorsque je modifie la valeur en supprimant les caractères de la droite vers la gauche.

Peux-tu m'indiquer si tu as un problème quand tu modifies la date à partir de la fin.
Si tu n'as pas de problème dans ce cas là, je pense que le problème est beaucoup moins problématique et qu'on peut fermer cette issue.

**Comment by guillett** [comment]
@monbocal comme vu ensemble. Le problème est désormais trop peu important pour y consacrer du temps.
