### ISSUE TITLE
Préciser ce que signifie "Total depuis X Y"

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#496]
Je reçois un grand nombre de mails de bénéficiaires potentiels qui s'interrogent sur la case "Total depuis mois année". Il faudrait expliciter cette case avec un texte ou un tooltip :)

**Comment by monbocal** [comment]
Mail du 15/03/17 20:50 : on a reçu une explication pour cette incompréhension;
"La [quatrième] case vous demandez le total depuis mars 2016. Est ce le total de mars 2016 à novembre 2016 ? puisque decembre 2017 est noté dans la première case."

**Comment by monbocal** [comment]
Après investigation de ma part : le fichier à modifier est capture-montant-ressources.html . Les mois et années sont codées avec des variables et je n'arrive pas à les retrouver. Je ne suis pas en mesure de prendre cette modification à l'heure actuelle.

**Comment by guillett** [comment]
La proposition dans #553 est un retour en arrière.

> “Total des douze derniers mois” c’était ce qui était affiché avant. On avait changé parce que les utilisateurs trouvaient ça ambigus

Il nous manque de l'historique pour être intéressant.

@MattiSG aurais-tu des éléments de clarification ?

**Comment by MattiSG** [comment]
+1 mail du 16 mai 2017 à 10:28:25 UTC+2

**Comment by MattiSG** [comment]
> aurais-tu des éléments de clarification ?

Non, je ne m'en souviens pas. Je pense qu'il y a toujours un risque du type « douze derniers mois, c'est l'année civile ou pas ? ». Il y a tellement de comptages différents selon l'administration à laquelle on demande…

La proposition apportée par l'utilisateur le 16 mai 2017 à 10:28:25 me semble très bien :

> mettre plutôt « vos revenus depuis mai 2016 à avril 2017 » à la place de « vos revenus depuis mai 2016 »

**Comment by MattiSG** [comment]
Ou sinon on change la logique et on demande la somme des mois m-12 à m-4, et on fait la somme nous-mêmes. C'est peut-être pas plus bête, vu qu'il faut de toute façon faire une somme ; le seul inconvénient est pour les personnes qui ont des revenus totalement stables et qui peuvent connaître leurs revenus annuels.

**Comment by monbocal** [comment]
Je suis pour ma part convaincu que la proposition de #553 n'est pas un retour en arrière à partir du moment où la PR ajoute en plus un descriptif détaillé au survol détaillant les mois concernés. On peut faire beaucoup pour modifier cette page dans sa globalité : dans l'immédiat, je trouve que cette solution peut résoudre bien plus de problèmes qu'elle ne pourrait en reposer à nouveau.

**Comment by monbocal** [comment]
J'ai eu une épiphanie qui va dans le sens de @MattiSG : demander la somme m-12/m-4 certes, mais avec une réorganisation des cases dans l'ordre chronologique.

Total M-12 à M-4 / M-3 / M-2 / M-1

**Comment by MattiSG** [comment]
Fixed via #573.

@guillett penser à mettre à jour toutes les issues références lors d'un merge :)
