### ISSUE TITLE
Tests d'intégration avec SauceLabs

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ui#516]
En regardant l'intégration dans la CI des tests d'intégration je suis tombé sur :
https://github.com/sgmap/mes-aides-ui/search?q=saucelabs&type=Issues&utf8=%E2%9C%93

J'ai l'impression que les tests d'intégration faisaient partie de la CI mais ce n'est plus le cas aujourd'hui.

- Est-ce bien le cas ?
- Pensez-vous qu'il serait intéressant de (re)mettre ça en place ?
- Si non, pourquoi ? (fréquence des faux négatifs ?)

**Comment by MattiSG** [comment]
Peux-tu être plus précis sur les éléments auxquels tu fais référence stp ?

Attention à ne pas confondre tests d'intégration, tests d'intégration sur SauceLabs, tests d'intégration en CI, et tests d'intégration en CI sur SauceLabs…

Je ne crois pas qu'on ait jamais fait tourner les tests d'inté en CI, non, tout simplement car l'installation de la totalité de la stack était compliquée pendant longtemps (comme tu l'as vu toi-même avec #515 par exemple).

**Comment by guillett** [comment]
Je ne fais pas référence à des éléments en particulier :-). J'ai ouvert cette _issue_ pour regrouper les informations autour des tests d'intégration et leur possible mise en place en CI peut-être via SauceLabs.

Ton commentaire répond à mes premières questions.
Voilà mes commentaires et interrogations complémentaires :

Le commit https://github.com/sgmap/mes-aides-ui/commit/91051e59d32b6bbf3340a0bdd69515987234dc09 me donne l'impression qu'il est possible de `watai` en utilisant Selenium dans SauceLabs.

Est-ce bien possible ? Si oui comment ? (J'ai regardé dans mes-aides-ui et dans watai mais sans succès)

Il serait vraiment bien de mettre en place un service mes-aides (soit dans travis, soit dans circleCI, soit sur un VPS via la configuration puppet) et de l'utiliser pour lancer les test d'intégrations à partir des serveurs SauceLabs.

Cela vous semble-t-il aussi intéressant/réalisable/à valeur ajoutée ?

**Comment by MattiSG** [comment]
> Est-ce bien possible ? Si oui comment ?

https://github.com/MattiSG/Watai/wiki/Set-up-parallel-continuous-testing

> mettre en place un service mes-aides

Qu'entends-tu par « un service » ?

**Comment by guillett** [comment]
Merci, je vais faire des tests avec Watai et SauceLabs.

Par « service », je veux dire la stack complète de bon fonctionnement de Mes-Aides (MongoDB, une instance d'OpenFisca et une instance de Mes-aides).

**Comment by MattiSG** [comment]
Oui, il faut bien évidemment faire tourner toute la stack dans la CI (sur Circle, Sauce ne fait qu'exécuter un navigateur, par un applicatif). Ça fait d'ailleurs partie du test.

**Comment by guillett** [comment]
Fixed by #526
