### ISSUE TITLE
Revaloriser le RSA (septembre 2017)

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#521]
Source : http://www.gouvernement.fr/argumentaire/lutte-contre-la-pauvrete-le-rsa-augmentera-en-septembre

Impact : 
"Le RSA, dont le montant varie en fonction de la composition du foyer,  sera ainsi porté à 545 euros par mois pour une personne seule. Les décrets seront pris très prochainement."

Autres impacts (en attente de plus d'éléments concrets) :
"Les plafonds de ressources en vigueur pour l'accès à la CMU-C (couverture maladie universelle complémentaire) et pour l'aide à la complémentaire santé (ACS) seront également relevés. Près de 150 000 personnes bénéficieront ainsi d’une couverture complémentaire solidaire. L’allocation de soutien familial, le complément familial et l’allocation de solidarité aux personnes âgées ont également été revalorisés."

**Comment by guillett** [comment]
Fait par https://github.com/openfisca/openfisca-france/pull/767 via #569.
