### ISSUE TITLE
Préciser les conditions d'attribution des aides

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#533]
En tant que bénéficiaire potentiel d'une aide,
Je suis informé en fin de simulation des plafonds de revenus à ne pas dépasser et des conditions à remplir
Afin de pouvoir savoir quand est ce que je n'aurais plus accès à ces aides

-- -- --

Cette issue fait suite au mail reçu le 06/04/2017 à 19:35 . C'est une proposition qui soulève quelques considérations déontologiques : j'ouvre l'issue pour que vous m'en parliez et me donniez votre ressenti.

**Comment by MattiSG** [comment]
Cela me semble être un contre-sens pour Mes Aides, qui rend ces règles calculables. Les exposer revient à remettre de la complexité. Si le cas d'usage est un changement de situation prévisible, il faut pousser l'utilisateur à refaire une simulation en se projetant dans sa nouvelle situation. Sinon, le lien « Plus d'informations » permet d'accéder à tous les détails nécessaires pour comprendre les conditions d'éligibilité.
