### ISSUE TITLE
Page stats

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ui#551]

**Comment by guillett** [comment]
A minima : Voir le contenu de la branche `stats`.

**Comment by guillett** [comment]
Métriques (visites et conversions) en hebdo et mensuel.

**Comment by guillett** [comment]
Version de base

![capture d ecran 2017-11-03 a 16 03 17](https://user-images.githubusercontent.com/1410356/32380517-87f2963a-c0b0-11e7-8dcb-09fed43cb0dd.png)

@monbocal tu en penses quoi pour une v0.1 ? 🙂

**Comment by monbocal** [comment]
J'aime l'apparence, j'aime moins les creux dû au weekend. Qu'est ce que ça donne avec les visites hebdomadaires ?

**Comment by guillett** [comment]
La courbe _Simulations_ ne vient pas de Piwik mais de notre base de données. Je n'ai pas encore généré les données en hebdomadaire. Je voulais ajouter une phrase descriptive qui explique les creux.

**Comment by monbocal** [comment]
OK, la voilà dans ce cas !

Ces données proviennent de la base de données des simulations effectuées sur Mes Aides. Les creux reflètent un usage modéré de notre simulateur les samedis et les dimanches.

**Comment by guillett** [comment]
Une version de base a été mise en production.
Pour le moment cette page n'est pas mise en avant.
