### ISSUE TITLE
Mettre à jour la capture d'écran utilisée sur beta.gouv.fr

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ui#560]
@monbocal je ne connais trop tes disponibilités mais je me suis dis que c'est une modification que tu pouvais prendre ?

**Comment by monbocal** [comment]
Allez, je suis d'humeur arts plastiques aujourd'hui, je vais faire un collage

**Comment by monbocal** [comment]
Trois visuels possibles, préférence pour le 2. J'ai fait le 1 en premier sans en être satisfait. Le 3 c'est un copier coller de l'existant, mais qui d'un point de vue com', ne donne vraiment pas envie d'utiliser Mes Aides.
![mes-aides-redux-1](https://cloud.githubusercontent.com/assets/25476945/26197031/2aa78a7c-3bc1-11e7-8587-fc2bc836038b.png)
![mes-aides-redux-2](https://cloud.githubusercontent.com/assets/25476945/26197032/2aa7e544-3bc1-11e7-8ffb-f03205fd8d25.png)
![mes-aides-redux-3](https://cloud.githubusercontent.com/assets/25476945/26197033/2aab64e4-3bc1-11e7-94fc-be25c2bb85b5.png)

**Comment by guillett** [comment]
@monbocal, je partirai sur la 3ème. Je te laisse faire la PR ?

**Comment by monbocal** [comment]
Okey dokey lokey. La PR est au https://github.com/sgmap/beta.gouv.fr/pull/726

**Comment by Morendil** [comment]
Merged!
