### ISSUE TITLE
Ne pas permettre la modification d'une situation

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ui#576]
Une situation enregistrée ne doit pas être modifiable.

En cas de modification dans l'application, il faudrait indiquer l'ID de la situation originale dans l'attribut `previous_id` de la nouvelle situation par exemple.

**Comment by MattiSG** [comment]
Quel est l'intérêt de conserver un lien vers la situation originale ?

**Comment by guillett** [comment]
Lier les situations ajoute de l'information avec un coût négligeable :
- Durée entre une situation et une version altérée (si des usagers modifient des situations trop anciennes (ce qui est un peu le cas cf. 403 sur PUT `/api/situations/SITUATION_ID`.)
- Analyse des modifications effectuées sur les situations

**Comment by monbocal** [comment]
+1, c'est pratique quand on regarde les Montants inattendus et qu'on fait des tests pour savoir d'où vient la différence entre Mes Aides et les organismes, ça évite de devoir retaper une simulation dans un autre onglet pour faire des tests dessus.

**Comment by guillett** [comment]
Récupération rapide des données pour avoir une idée de l'impact sur le nombre de situation à enregistrer dans la base de données (via `__v`).

Nombre de modifications|Nombre de situations|Nombre de situations en cas de sauvegarde des différentes versions
-----------------------|--------------------|-------------------------------------------------------------------
0|475835|475835
1|227775|455550
2|80710|242130
3|25320|101280
4|11450|57250
5|5063|30378
6|2665|18655
7|1401|11208
8|893|8037
9|551|5510
10|329|3619
11|231|2772
12|172|2236
13|119|1666
14|68|1020
15|59|944
16|55|935
17|49|882
18|20|380
19|25|500
20|25|525
21|14|308
22|18|414
23|14|336
24|9|225
25|6|156
26|8|216
27|4|112
28|9|261
29|1|30
30|4|124
31|4|128
32|7|231
33|5|170
35|2|72
36|4|148
37|5|190
38|3|117
39|3|120
40|4|164
41|2|84
42|2|86
44|3|135
45|2|92
46|1|47
49|1|50
52|1|53
54|1|55
59|2|120
72|1|73
76|1|77
91|1|92
108|1|109
115|1|116
120|1|121
138|1|139
142|1|143
148|1|149
190|1|191
200|1|201
220|1|221
Total|832966|1427188

**Comment by guillett** [comment]
Implémenter dans #628
