### ISSUE TITLE
Utiliser un formulaire de contact plutôt qu'un envoi d'email

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#577]
(issue pour que je m'en souvienne)

En cliquant sur les liens "Ces résultats ne correspondent pas", si l'user n'a pas configuré de client mail, alors ça lui fait peur / "ça marche pas votre truc" car un client mail non configuré s'ouvre. Trouver une autre méthode pour pouvoir capter les utilisateurs ?

**Comment by monbocal** [comment]
C'est surtout vrai pour la fin de la simulation, c'est le seul moyen pour récupérer l'ID de simulation, c'est barbare :/

**Comment by MattiSG** [comment]
La seule alternative est de maintenir un formulaire de contact. Cela a rapidement un coût élevé, car il faut gérer la boucle retour si l'on veut pouvoir communiquer avec l'usager.

**Comment by guillett** [comment]
Deprecated par #583
