### ISSUE TITLE
Faire fonctionner la restauration sessionStorage

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#58]
Sous Firefox 37.0.2 sur une Fedora 22, la restauration de session ne fonctionne pas (#54).

Une entrée `sessionStorage` est bien existante, mais elle ne contient pas les informations de situation.
![session_mes_aides](https://cloud.githubusercontent.com/assets/1479859/7338523/92989438-ec4e-11e4-8c45-1fe38c45d454.png)
Il s'agit de la [valeur par défaut](https://github.com/sgmap/mes-aides-ui/blob/57a549b3c62fc050b75614e5ed1cb3dce5bb2c40/app/js/services/situationService.js#L60-L62).

Repéré par @moimael (merci !).

**Comment by Flightan** [comment]
Je n'arrive pas à reproduire sur Firefox 37.02 et OSX Yosemite.

**Comment by MattiSG** [comment]
@moimael Le `sessionStorage` n'est valide que jusqu'à ce qu'on recommence une simulation depuis la page d'accueil : le bouton "Commencer la simulation" réinitialise le storage. Est-ce ce que tu as fait, ou as-tu simplement rechargé la page ?
Dans le premier cas, c'est un problème de découvrabilité de l'usage, dans le second c'est un bug.

**Comment by moimael** [comment]
Problème de découvrabilité dans ce cas, effectivement en retournant sur le site plus tard je m'attendait a reprendre ou j'en étais, soit directement soit en cliquant sur commencer la simulation. Le fait de sauvegarder la progression uniquement si on ne quitte pas la page a peu d’intérêt AMHA.

**Comment by MattiSG** [comment]
Super, merci pour l'investigation @Flightan et pour le retour @moimael !  :)  Je ferme cette issue en tant que bug et met un compte-rendu dans #54, à dépiler quand on la traitera.
