### ISSUE TITLE
Aides manquantes

### ISSUE THREAD

**Issue by Astaoth** [sgmap/mes-aides-ui#6]
Bonjour,

Je me doute que des fonctionnalités et des aides vont être ajoutés au fur et à mesure, mais au cas où, les aide loca-pass, mobi-pass et mobi-jeune ne sont pas indiqués. C'est dommage, parce que ca aurait enfin pû fournir un moyen de connaître le montant réel accordé par l'aide mobi-jeune en fonction de la situation.

**Comment by MattiSG** [comment]
Bonjour @Astaoth et merci pour l'idée ! Nous cherchons évidemment à ajouter de plus en plus d'aides.

Pour faciliter le suivi des demandes, nous allons créer une issue par aide demandée, afin que toute personne se sentant concernée puisse ajouter un +1, et suivre l'évolution.

Si tu es toujours intéressé par les aides que tu évoquais, merci de créer une issue pour chacune d'entre elles, avec la référence la plus officielle possible vers le descriptif de l'aide. Dans l'idéal, nous cherchons les conditions d'attributions et les modalités de calcul.

Dans tous les cas, merci pour ta contribution !  :)
