### ISSUE TITLE
Informer de la condition de non-versement de pension pour l'ASF

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#60]
En tant que bénéficiaire potentiel de l'ASF,
Je sais que mon éligibilité dépend du non-versement de la totalité d'une pension alimentaire,
Pour déterminer mon éligibilité

- - - - 

L'implémentation complète nécessite une refonte à la fois de la capture des montants attendus et réels des pensions alimentaires reçues, et de la présentation des résultats. En attendant d'avoir accompli #22, un texte d'information lié à l'ASF fera l'affaire.

**Comment by MattiSG** [comment]
@HelaG Est-ce que ce test est juste ? https://mes-aides.gouv.fr/tests/5547ca25301cd06239697da2/show

**Comment by HelaG** [comment]
Au niveau du mécanisme c'est ça. ASF différentielle = (ASF totale * nbre d'enfants) - somme des pensions alimentaires effectivement perçues.
Par contre, dans le test, pourquoi est-ce que tu prends en compte les 30€ de prestation compensatoires à la place des 20€ de pensions alimentaires?

PI, le dispositif semble être en cours d'expérimentation : https://www.caf.fr/ma-caf/caf-de-paris/actualites/annee/2014/experimentation-des-garanties-contre-les-impayes-de-pensions-alimentaires-gipa

**Comment by MattiSG** [comment]
> pourquoi est-ce que tu prends en compte les 30€ de prestation compensatoires à la place des 20€ de pensions alimentaires?

Justement pour lancer la discussion sur laquelle des deux doit être prise en compte  :D  Ça n'est pas clair pour moi : l’ASF vient complémenter l’alimentaire ou la compensatoire ?

**Comment by HelaG** [comment]
:) OK!
L'ASF vient compléter la pension alimentaire (qu'un ex-conjoint verse pour l'entretien des enfants).

La prestation compensatoire c'est ce qu'un ex-conjoint verse à son ex pour "compenser" la baisse de son niveau après leur séparation. La Caf n'intervient pas dans ce cas.

**Comment by MattiSG** [comment]
Parfait. On va pouvoir créer une nouvelle issue sur ce sujet, du coup.
