### ISSUE TITLE
Capturer le CLCA

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#61]
En tant que bénéficiaire potentiel de la CMUc/ACS,
Je peux renseigner le montant de mon CLCA/PrePaRe,
Pour déterminer le montant de mon ACS

- - - -

Le [CLCA](https://www.caf.fr/aides-et-services/s-informer-sur-les-aides/petite-enfance/le-complement-de-libre-choix-d-activite-ou-le-complement-optionnel-de-libre-choix-d-activite) (et, depuis le 1er janvier 2015, [PrePaRe](https://www.caf.fr/aides-et-services/s-informer-sur-les-aides/petite-enfance/la-prestation-partagee-d-education-de-l-enfant-prepare-ou-la-prestation-partagee-d-education-de-l-enfant-majoree-prepare-majoree)) sont pris en compte dans la base de ressources pour la détermination de la CMUc/ACS.

Les conditions de calcul contiennent un nombre de trimestres de retraite. Il faut donc repenser assez fortement l'interface sur cette capture. Dans un premier temps, on va capturer le montant comme une ressource.

**Comment by Anne-LaureM** [comment]
J'ai fait 2 tests sur la capture du CLCA en jouant sur le plafond CMUC (pour 3 personnes)
L'un est vert https://mes-aides.gouv.fr/tests/55643d7ba0084c3b26e9c8c7/show?keyword=cmu-c%252Facs
L'autre rouge https://mes-aides.gouv.fr/tests/55643f366aca6d3826e553a4/show 
Est-ce que l'on est bien sûr que le CLCA entre dans le calcul CMUC/ACS?

**Comment by fpagnoux** [comment]
Dans les deux cas, le foyer est bénéficiaire du RSA, donc attribution
automatique de la CMU ;)

**Comment by Anne-LaureM** [comment]
Merci Florian! du coup j'ai corrigé le test pour qu'il n'y ait pas de RSA. 
https://mes-aides.gouv.fr/tests/55643f366aca6d3826e553a4/show

**Comment by fpagnoux** [comment]
@Anne-LaureM a trouvé un bug, c'est corrigé mais en attente de déploiement

**Comment by Anne-LaureM** [comment]
Communication à la CNAMTS faite
