### ISSUE TITLE
"On y est presque !" : modification de la formulation

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#618]
Suite à un retour utilisateur de la formulation "On y est presque !", je pense que la formulation est maladroite.

Utilisateur :
>  Je trouve que pour les personnes pour qui l'obtention de cette complémentaire est urgente, peut-être, vitale, du moins conditionne l'accès à des soins importants ; cette interjection peut paraître dédaigneuse, méprisante : "on y est presque", pourquoi pas : "Retente ta chance", "Reviens le mois prochain" ou mieux "Encore un effort !".... C'est familier et cela sonne condescendant. Bien sûr tout dépend de la façon de voir si le verre est plein ou à moitié vide. Mais quand on est malade ...!
> 
> La mode en communication est d'user de ces phrases à connotations "positives" "amicale" mais vide de sens. Cela dit un  : " Nous sommes désolés. La somme de vos ressources sur les 24 derniers mois ...etc.", est factuel et sans désillusions. Surtout venant d'une interface logicielle automatisée et systématique. Après je ne suis pas rédacteur web. Si vous aviez affiché la différence entre le montant des ressources déclarées et le plafond établit par la loi dans un message du style : " Vous dépassez le plafond de ressources de ...", cela ferez réfléchir en donnant une indication utile.

Le "On y est presque !" tranche beaucoup à mon sens avec le reste du ton du simulateur. Si son but est de préciser qu'on est presque arrivé à la fin des éléments demandés, alors l'interprétation "on est presque prêt à avoir une aide !" est également possible. D'où mon soucis : je pense que c'est cette ambiguïté qui est à lever.

@guillett 
> Le commentaire est intéressant, je comprends la perception que Fabrice a de la formulation. En même temps, je considère aussi que cette formulation est une façon de souligner l’effort déjà fourni par l’usager (avec la saisie du détail des ressources).
> 
> Cela dit, je pense qu’une reformulation serait effectivement bienvenue sachant que le «  On y est presque » est affiché en cas de non-éligibité à toutes les aides et lorsque les ressources YM2 n’ont pas encore été spécifiées.

**Comment by guillett** [comment]
@monbocal te rappelles-tu de la formulation dont on avait discuté au bureau ?

**Comment by monbocal** [comment]
Non. On en reparle demain ?

**Comment by guillett** [comment]
Fait dans #677
