### ISSUE TITLE
Les pensions alimentaires versées n’apparaissent pas dans le recapitulatif de droite

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ui#624]
Sauf en cas de rechargement complet de la page.

Related to #620.

**Comment by guillett** [comment]
@monbocal as-tu réussi à faire apparaitre les pensions alimentaires versées dans le récapitulatif de droite en production ?

De mon côté, j'y arrive pas.

Cela dit, si ça n'apparait pas en production c'est un bug.
A voir si c'est corrigeable facilement et directement dans #620.

**Comment by monbocal** [comment]
Elles sont apparus dans le récap de droite sur VPS avec les modifs que tu as faites

**Comment by guillett** [comment]
C'est bon pour moi.
