### ISSUE TITLE
Informer de la condition de résidence pour le RSA

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#63]
En tant que bénéficiaire potentiel du RSA,
Je suis informé de la condition de résidence,
Pour déterminer mon éligibilité

**Conditions** :

Résider en France depuis plus de :
- 3 mois pour un ressortissant UE/EEE/Suisse.
- 5 ans pour un ressortissant autre.

Pour tous :
- Résidence stable et effective en France (pas plus de 3 mois en dehors de France par année civile ET de date à date).

**Comment by MattiSG** [comment]
@HelaG La condition de résidence de 5 ans pour un ressortissant non UE est-elle en réalité celle d'être porteur d’une carte de [résident longue durée](http://vosdroits.service-public.fr/particuliers/F17359.xhtml) ?

**Comment by HelaG** [comment]
Tout étranger qui vit en France depuis 5 ans peut être bénéficier du RSA.
Tout étranger qui vit en France depuis 5 ans n'a pas forcement de carte "résident longue durée". 
Il peut continuer à renouveller tous les ans son titre de séjour, être "en règle" et être éligible au RSA.

**Comment by MattiSG** [comment]
Super, merci beaucoup pour la clarification !  :)
