### ISSUE TITLE
Mettre à jour la liste des communes nouvelles

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#652]
Chaque année, de nouvelles communes sont créées suite à la fusion d'anciennes communes. De ce fait, la base proposée sur Mes Aides n'est plus à jour et peut proposer des communes qui n'existent plus.

Ex: 74600 Seynod n'existe plus depuis le 1er janvier 2017, c'est 74600 Annecy à la place.

Liste : https://fr.wikipedia.org/wiki/Commune_nouvelle

**Comment by monbocal** [comment]
+1, j'ai eu un Francheville aujourd'hui

**Comment by guillett** [comment]
C'est à suivre sur https://github.com/etalab/codes-postaux/

**Comment by monbocal** [comment]
Je n'ai pas compris, je dois faire l'issue là bas ?

**Comment by guillett** [comment]
Non, je vais avoir eux ce qu'il est possible de faire.

**Comment by guillett** [comment]
OK pour 74600, les données proviennent de l'API Géo que je considère être la meilleure source à jour.
