### ISSUE TITLE
Ajout des indications pour la personnalisation des liens

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ui#666]
Créer une section à la fin de la page du wiki https://github.com/sgmap/mes-aides-ui/wiki/Personnalisation-des-liens-associ%C3%A9es-aux-aides-sociales) et indiquer les modifications techniques à faire dans le code mes-aides.

**Comment by guillett** [comment]
Up

**Comment by monbocal** [comment]
Heu j'ai un doute : je dois expliquer coder ça dans Mes Aides (avec les fichiers à citer et les choses à modifier) ou bien expliquer qu'on peut le faire ?

**Comment by guillett** [comment]
🤔 Je ne suis plus non plus.
Là je me dis que des éléments compréhensibles par un _business developer_ seraient intéressants.

Je pense en particulier à la définition de la personnalisation (ville/département/région/liste de villes).
Peut-être aussi indiquer les modifications à faire sur le fichier `droits.js`.

Sinon on en discute lundi prochain.

**Comment by guillett** [comment]
Finalement on considère que ça ne vaut pas le temps passé.
