### ISSUE TITLE
Rediriger le flux des usagers provenant d'assure.ameli.fr

### ISSUE THREAD

**Issue by guillett** [sgmap/mes-aides-ui#670]
Un nombre important d'usagers provient d'assure.ameli.fr mais ce trafic n'est pas très qualifié.

Il faudrait gérer ce flux dès la page d'accueil grâce à l'information `referrer`.

**Comment by guillett** [comment]
Pourrais-tu lister les raisons pour lesquelles les usagers de Améli viennent chez nous. L'idée est de les rediriger vers une page spécifique pour mieux répondre à leurs problématiques.

**Comment by monbocal** [comment]
Le plus important : la mutuelle :
- Mutuelle non indiquée sur l’espace
- Renouvellement de mutuelle (CMU) (dont informations sur le traitement de la demande)
- Association de la mutuelle à d’autres membres de la famille
- Je n’ai pas de mutuelle, je demande la CMU-C

Ensuite, les problèmes d’accès au compte :
- Je n’ai pas / plus mes identifiants
- Je n’ai que mon numéro de carte vitale

**Comment by monbocal** [comment]
Comment tu vois ça : veux-tu un texte explicatif ? Je dois avoir des liens pour les différents cas.

Peut-être un vieux "Vous avez quitté le site de l'Assurance Maladie pour vous rendre sur Mes Aides. Dans quel cas vous trouvez-vous ?" avec des liens de retour sur Amelie ?

**Comment by monbocal** [comment]
Besoin du texte et des liens
