### ISSUE TITLE
Déplier / Replier

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#696]
Afin d'inciter à cliquer sur le nom des aides afin de trouver les documents, je pense qu'il faudrait tester une action textuelle en plus des chevrons actuellement présents :

"Déplier >" puis "Replier v" ?
"Montrer plus >" puis "Montrer moins v" ?

**Comment by monbocal** [comment]
Trois scénarios à tester pour regarder ce qui marche le mieux :

- scénario actuel avec les chevrons
- avec fa-minus-circle et fa-plus-circle à la place des chevrons
- avec Déplier / Replier à la place à des chevrons

Objectif : comptabiliser les liens sur les clics sortants dans chacun des scénarions afin de pouvoir améliorer cette page.

**Comment by guillett** [comment]
En fait, on va :
Tout déplier par défaut et
Remplacer les chevrons par des + et des -

**Comment by guillett** [comment]
Comme vu ensemble, les + et les - près des montants n'est pas idéal.
Déplier tout par défaut cache le CTA vers la déclaration des revenus 2015 et du patrimoine.
L'ajout des chevrons sur les petits écrans est suffisant.
Je ferme l'issue.
