### ISSUE TITLE
Préciser la date butoir pour les demandes de bourse

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#699]
Pour la bourse de lycée et la bourse de collège, il y a une date butoir à respecter selon les années :

Pour 2017/2018 :
- Lycée : 20/07/2017 pour la 1re demande
- Collège : 18/10/2017

En gros, on peut continuer à les annoncer, mais il faudrait afficher leur date limite dans leur description.

**Comment by guillett** [comment]
Fixed by #712
