### ISSUE TITLE
Modification des liens Facebook

### ISSUE THREAD

**Issue by monbocal** [sgmap/mes-aides-ui#719]
https://www.blogdumoderateur.com/modifier-apercu-liens-facebook/

**Comment by monbocal** [comment]
Trois façons sont possibles :
- modification du DNS
- upload d'un fichier de vérification
- modification d'un meta tag

La modif DNS est le plus secure mais le plus risqué à mettre en place.
L'upload d'un fichier est le plus rapide et le plus sale (tout le monde aura accès à notre code de vérification)
La modification d'un meta tag est possible et pas trop risqué (l'ID de la page est publique)

Qu'est ce que tu préfères @guillett ?

**Comment by guillett** [comment]
@monbocal je te laisse ajouter le tag meta, ok ?

**Comment by monbocal** [comment]
OK tag meta c'est parti

**Comment by guillett** [comment]
Fixed by #728
