### ISSUE TITLE
Barème HLM

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#74]
En tant que locataire,
Je peux signaler que je vis en HLM,
Pour déterminer le montant de mon aide au logement

### Communication

- [x] wiki
- [ ] tweet

**Comment by HelaG** [comment]
A priori le fait d'habiter en HLM n'impacte pas le mode de calcul des aides au logement. 

Si je suis [locataire en HLM](http://www.caf.fr/aides-et-services/s-informer-sur-les-aides/logement-et-cadre-de-vie/les-aides-au-logement-0), et que mon bailleur est conventionné avec l'Etat alors je suis éligible aux APL en secteur locatif; qui se calculent comme les AL. Pas de barème spécifique. 

La seule information spécifique qui concerne les locataires en HLM est le mode de versement de l'aide; qui est directement versée au bailleur.

**Comment by fpagnoux** [comment]
Openfisca fait la distinction entre APL et AL, et entre location HLM et standart.  
Mais si il n'y a pas d'impact sur le résultat final, on peut faire comme si le locataire n'était pas en HLM. 

Par contre, il y a une grosse confusion dans Openfisca entre foyer et HLM. Pas d'impact direct sur mes aides, mais ça pourrait poser problème à terme. Je suis dessus.

**Comment by HelaG** [comment]
Effectivement il risque d'y avoir un problème quand on s'attaquera au cas "foyer"

Pour un locataire en HLM, on calcule des APL en appliquant le barème locatif commun à toutes les AL.
Pour un résident en foyer, 2 barèmes différents s'appliquent (en fonction de la nature du foyer)

**Comment by fpagnoux** [comment]
La distinction est maintenant faite entre HLM et foyer dans Openfisca. Pour quelqu'un en foyer, on ne calcule pas les AL et on renvoie vers la CAF. Pour un HLM, on ne fait pas de distinction avec une location standard. 
A priori rien de plus à implémenter, juste le wiki à documenter

**Comment by HelaG** [comment]
Super! 
Done pour le wiki.
Juste une question : quand tu dis on renvoie vers la Caf, c'est vers le [https://wwwd.caf.fr/wps/portal/caffr/aidesetservices/lesservicesenligne/estimervosdroits/lelogement/!ut/p/a1/lZDNDoIwEISfxQcwnVp_4NiAQKkK_qDCxTRGTaNUg8bntyQeDIkY97bJN7M7QwqyJYVRT31SD3016lLvxXCXJjSM5BIhxj0HIkLKomjNkPQskFsAX4ajVe_grW8BftzfkKKB-KkP4SKWrjugoaRNwAm8wAID35_Nhf2R_QLwBlpC5jbF6MNhljDwMKWOjD0K9ElmrlVp-1zWXseqPHtGHfm-bpnk1UEb_dDqou-HqumVUO5CLCYyDoYMNt8_Xrcy20KLbl7upive6bwA5ZjMGA!!/dl5/d5/L3dDcEEvd0NvQk1rQkEvNE8weENPd2cvWjZfUE8xR0hLUzBHMEUyODBJSDBQM0hIVjMwTzIvWjdfUE8xR0hLUzBHTzFBOTBJUkxLSkY2MzAwRzA!/simulateur de la Caf]?

**Comment by fpagnoux** [comment]
Oui, c'est bien sur cette page qu'on le renvoit
