### ISSUE TITLE
Neutralisation des revenus non professionnels

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#77]
En tant que bénéficiaire potentiel du RSA,
Mes revenus non salariés interrompus sont professionnels dans la limite du montant forfaitaire,
Pour déterminer mon éligibilité au RSA

Tests : [Ludwig](https://mes-aides.gouv.fr/tests/54bfdf50d337b5d372377d50/show)

### Communication

- [x] wiki
- [x] DGCS

**Comment by HelaG** [comment]
Alors j'ai rien trouvé comme infos pour les autres ressources non-pro (hors prestation compensatoire et pensions alimentaire). 

Mais, bonne nouvelle, les montants du CLCA et de la PreparE sont inférieurs au montant forfaitaire du RSA pour 1 personne, donc quelque soit la règle de neutralisation appliquée, ces deux presta sont réduites à 0 dans la base ressource du RSA si elles ne sont plus perçues le mois m.

**Comment by fpagnoux** [comment]
Implémenté pour les pensions alimentaires et compensatoires. 
Reste à avoir un retour sur le test de Marion Tonnes qui ne passe pas, car pour elle l'abattement maximal est le montant forfaitaire moins le forfait logement.

**Comment by HelaG** [comment]
Le [test] (https://mes-aides.gouv.fr/tests/54bfdf50d337b5d372377d50/show) était faux. 
Les revenus non-pro qui ne sont plus perçus sont effectivement neutralisés dans la limite du montant forfaitaire du RSA socle pour une seule (sans déduction du forfait logement).
J'ai corrigé le test, mais il est encore rouge... J'ai l'impression qu'on applique une neutral totale des ressources.

**Comment by fpagnoux** [comment]
Normal que le test soit rouge, les changements n'ont pas été mis en production :)

**Comment by fpagnoux** [comment]
Précision sur la neutral des revenus non-pro : 
Si plusieurs des revenus ont été interrompus, est-ce que le montant forfaitaire s'applique pour chaque ressource, ou sur le total des ressources ?  
Ex: je touchais une pension alimentaire et une pension compensatoire jusqu'au mois M-2, chacune de 500€.  Elles sont interrompues depuis le mois M-1. Est-ce que je déduis une fois le montant forfaitaire, ou deux fois ?

**Comment by HelaG** [comment]
On déduit le montant forfaitaire de chaque ressource interrompues. 
Donc dans la BR, on retrouve (PA-MF) + (PC-MF).

Par contre, la neutral s'applique uniquement si la ressource n'est plus perçue au mois M 
(si je percevais une pension alimentaire en avril et que je ne la perçois plus en mai, on ne la neutralise pas en juin)

**Comment by fpagnoux** [comment]
Je ne suis pas sûr de comprendre ta dernière remarque. 
Si je prends un cas concret : je touche une pension alimentaire de 800€ au mois  M-3, M-2, mais plus à partir du mois M-1. 
Dans ce cas, quel sera le revenu à prendre en compte pour le calcul du RSA au mois M ? Je vois trois possibilités. 
- ((800 - MF) + (800-MF) + 0) /3, si on applique l'abattement seulement sur les mois où la pension a été versée
- (800 + 800 + 0) /3 - MF si on applique l'abattement sur la moyenne des trois dernières mois
- 800 si on ne fait pas d'abattement. 

Qu'est ce que tu en penses ?

**Comment by HelaG** [comment]
Dans le cas que tu décris, il n'y a pas de neutralisation la BR est donc égale à (800+800+0)/3

Si j'ai reçu des PA sur les 3 derniers mois, mais je ne la recevrai pas au mois m, alors la BR est égale à [(800+800+800)/3] - MF

ça te paraît logique?

**Comment by fpagnoux** [comment]
Ça me parait franchement étrange. Je ne vois pas  pourquoi  d'un côté on abattrait pour une personne qui vient de perdre un revenu, mais de l'autre on conterait à taux plein pour une personne qui a perdu ce revenu il y a un mois. 
Je ne vois pas non plus de référence à cette règle sur [l'article de loi](http://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074069&idArticle=LEGIARTI000006906133&dateTexte=&categorieLien=cid), ni [ici] (http://insertion.maine-et-loire.fr/fileadmin/insertion/professionnels/guides/Guide_allocation.pdf) (p22)

**Comment by HelaG** [comment]
La neutralisation sert à "imaginer" la situation du demandeur pendant les 3 mois à venir. S'il déclare ne plus percevoir les ressources au mois M on applique la neutral.
J'ai créée le [test](https://mes-aides.gouv.fr/tests/5579b00178ebb479142d5c8f/show)

**Comment by fpagnoux** [comment]
Ok, je l'ai implémenté comme le dit la CAF alors :)

**Comment by fpagnoux** [comment]
See [PR](https://github.com/openfisca/openfisca-france/pull/274)
