### ISSUE TITLE
Pouvoir déclarer des personnes à charge de plus de 25 ans

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#78]
En tant que bénéficiaire potentiel ayant des personnes âgées à charge,
Je peux déclarer la composition de mon foyer,
Pour déterminer mon éligibilité à ???

- [x] Déterminer les aides impactées par des personnes à charge de plus de 25 ans — @HelaG @Anne-LaureM.
- [x] Déterminer si l'usage des “enfants” dans OpenFisca est en réalité “personne à charge” — @fpagnoux.
- [x] Modifier message d'introduction écran personnes à charge.
- [x] Modifier message d'erreur validation < 25 ans.

**Comment by Anne-LaureM** [comment]
L'ASPA, l'ASS et la CMUC/ACS ne prennent pas en compte les personnes à charge de plus de 25 ans dans la composition du foyer

**Comment by HelaG** [comment]
Les [prestations familiales](http://vosdroits.service-public.fr/particuliers/F16947.xhtml) et le [RSA](http://vosdroits.service-public.fr/particuliers/F20199.xhtml) ne prennent pas en compte les personnes à charge de plus de 25 ans.

**Comment by HelaG** [comment]
Donc on ne prend pas en compte les personnes à charge de plus de 25 ans dans les aides simulées aujourd'hui.

Est-ce qu'on permet quand même à un usager de déclarer une personne à charge > 25 ans ? (pour d'éventuelles prestations à venir qui les prendraient en compte et pour éviter le texte rouge un peu agressif "Cette personne ne peut pas avoir plus de 25 ans")

**Comment by MattiSG** [comment]
Si aucune des prestations actuellement calculées ne l'utilise, non. Ce sera un chantier tiré par la première prestation qui le nécessite.
Pour ce qui est du texte rouge, dans la mesure ou le titre de la section est clair ("Vos enfants et personnes à charge de moins de 25 ans"), ce n'est pas parfait mais est justifiable.
Si on a des retours utilisateur dans ce sens, on se reposera également la question.

En revanche, un point à éclaircir pour clore proprement cette discussion : @fpagnoux, est-ce qu'OpenFisca fait un traitement spécifique "enfants" ou bien gérer des personnes à charge de plus de 25 ans ne serait-il un changement qu'au niveau de l'interface graphique ?

**Comment by fpagnoux** [comment]
Pour Openfisca, il n'y a qu'un "chef de famille" (sic) qui est pour nous le demandeur, un partenaire,  et des enfants. Donc pas de différence fondamentale dans le code.

**Comment by fpagnoux** [comment]
Est-ce que la formulation vous convient ? 
C'est peut-être un peu long. 

![image](https://cloud.githubusercontent.com/assets/11834997/8086829/af53ee9e-0f97-11e5-8287-7160bf6eab5e.png)


![image](https://cloud.githubusercontent.com/assets/11834997/8086812/a24fbe9e-0f97-11e5-8832-acd25ae727e6.png)

**Comment by Anne-LaureM** [comment]
Peut être "les personnes à charge de plus de 25 ans n'étant pas prises en compte dans les aides simulées, il n'est pas nécessaire de les renseigner"

**Comment by MattiSG** [comment]
Proposition de formulation plus courte : #103.

Malheureusement, changer le message d'erreur pour le rendre spécifique implique de rendre le formulaire spécifique à cet écran plutôt que de réutiliser le même formulaire partout. Le coût technique n'en vaut pas le bénéfice, j'ai donc amendé à minima dans #103. Ok ?
