### ISSUE TITLE
Traiter les conjoints sans carte de séjour valide

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#81]
En tant que bénéficiaire potentiel dont le conjoint est de nationalité hors UE et n'a pas de carte de séjour valide,
Je peux effectuer une simulation,
Pour utiliser le service

- Origine du besoin : tests usager du 13/05

### Traitement

- [x] Déterminer la prise en compte d'un conjoint étranger sans carte de séjour valide pour chaque prestation conjugalisée ou familialisée — @HelaG @AnneLaure-M
- [x] Déterminer si le conjoint doit être ajouté dans le foyer ou non.
- [x] Ne pas bloquer l'interface.

### Communication

- [x] wiki

**Comment by HelaG** [comment]
Pour le RSA, si le conjoint ou l'enfant n'a pas de titre de séjour valide, le droit est calculé sur le montant forfaitaire pour une personne seule (comme si l'utilisateur était le seul membre du foyer.)

**Comment by HelaG** [comment]
[http://droit-finances.commentcamarche.net/forum/affich-5775042-aide-au-logement-avec-conjoint-sans-papier](Pour les aides au logement) :

Pas d'infos officielle sur le cas où le conjoint n'a pas de titre de séjour. En général, les prestations caf sont soumises à la condition de régularité du séjour. Donc c'est soit le demandeur ne déclare pas son conjoint à la Caf, soit il le déclare et la Caf lui demandera de fournir un justificatif de séjour. 

On peut donc faire l'hypothèse, quand le conjoint est sans papier, de calculer les AL pour un couple en informant, en sortie de simulation, que la Caf vérifiera les conditions de séjour du conjoint.

**Comment by Anne-LaureM** [comment]
Pour l'ASS, PE ne vérifie pas la condition de séjour, il se base uniquement sur la déclaration du demandeur. Si un conjoint est déclaré (qu'il ait une carte de séjour valide ou non), PE prend en compte ses revenus dans le calcul du montant de l'ASS et le compte dans le couple du demandeur.

Pour la CMUC/ACS, la CNAMTS prend en compte le conjoint ayant une carte de séjour non valide dans le foyer  mais il ne pourra pas bénéficier de la CMUC/ACS. Il sera dirigé vers l'AME.

**Comment by Anne-LaureM** [comment]
Pour l'ASPA: la CNAV n'a pas d'instruction à ce sujet, elle a saisi la DSS il y a plusieurs mois sur la question, sans réponse de leur part. Elle relance la DSS et d'attente de la réponse, propose d'ici là, dans le cas d'un couple (demandeur et conjoint sans carte de séjour valide) d'appliquer le barême ASPA une personne tout en prenant en compte les revenus du conjoint le cas échéant.

**Comment by Anne-LaureM** [comment]
Si le demandeur déclare un conjoint sans carte de séjour valide, alors:
- on prend en compte son conjoint dans le foyer 
- on prend également en compte ses ressources
- on applique le barême correspondant à la structure couple
Pour le RSA et l'ASPA, il est possible que ce soit le barême personne seule qui soit appliqué mais, dans l'attente des textes réglementaires l'indiquant, le simulateur appliquera le traitement le plus favorable à l'usager.

**Comment by fpagnoux** [comment]
C'est déployé. Concrètement, on a juste désactivé toutes les questions de nationalité sur le conjoint et les enfants.
