### ISSUE TITLE
Améliorer le traitement des personnes sans domicile stable

### ISSUE THREAD

**Issue by MattiSG** [sgmap/mes-aides-ui#82]
En tant que bénéficiaire potentiel sans domicile stable,
Je peux déclarer ma situation,
Pour exister aux yeux de l'administration

- [x] Remplacer le texte explicatif par un statut à part entière « sans domicile stable ».
- [x] Déterminer le traitement à appliquer sur le forfait logement du RSA — @HelaG.
- [x] Déterminer le traitement à appliquer sur le forfait logement de la CMU-C — @Anne-LaureM.
- [x] Déterminer la situation à construire dans OpenFisca.
- [x] S'assurer que les AL sont neutralisées.
- [x] Comprendre la procédure de domiciliation - @Anne-LaureM
- [ ] Valider l'engagement à la domiciliation en début de phase de démarches - @MattiSG
- [x] Déplacer le champ d'adresse en début de procédure et ajouter une redirection en cas de SDF - @fpagnoux

**Comment by Anne-LaureM** [comment]
Pour la CMUC/ACS, le forfait logement n'est pas appliqué lorsque la personne est "hébergée" en foyer d'accueil.

**Comment by HelaG** [comment]
Pour le RSA, le forfait logement n'est pas appliqué pour les personnes sans domicile fixe (comme pour les personnes occupants à titre gratuit).

**Comment by HelaG** [comment]
+1 utilisateur à la conf de presse 01/06

**Comment by fpagnoux** [comment]
Si quelqu'un est sans domicile stable, est-il pertinent d'après vous de lui demander son code postal ?

**Comment by HelaG** [comment]
Quand la question s'est posée, j'étais avec un usager, sans domicile fixe, mais qui a directement répondu "78200 Mantes la Jolie" pour le CP

**Comment by fpagnoux** [comment]
On indique aujourd'hui dans la page de saisie du logement : 
"Si vous n’avez pas de domicile fixe ou stable, vous devez effectuer une [demande de domiciliation](http://vosdroits.service-public.fr/particuliers/F17317.xhtml) ."
Est-ce que ce message est à conserver ici, supprimer, ou poster à la fin comme condition nécessaire à l'attribution des prestations ?

**Comment by HelaG** [comment]
A mon avis, l'usager qui a cliqué "sans domicile fixe" doit avoir cette information, donc :
- soit elle apparait sur la page logement quand il a cliqué sur SDF, 
- soit en diclaimer en fin de simu, l'info concerne toutes les presta (pas seulement les aides au logement) donc il faut pouvoir la faire apparaitre en dehors des encarts par aides.

**Comment by fpagnoux** [comment]
Ok, dans ce cas je pense qu'il faut mieux la faire apparaître quand le
demandeur clique sur sans domicile stable

**Comment by MattiSG** [comment]
> Si quelqu'un est sans domicile stable, est ce qu'il est pertinent d'après vous de lui demander son code postal ?

Oui, pour les aides territorialisées qui vont très bientôt être ajoutées. Le bénéficiaire peut être SDF sans domiciliation "officielle" mais être potentiellement éligible à certaines aides territorialisées lorsqu'il aura faita sa demande de domiciliation, et il sait déjà où il la fera.

**Comment by Anne-LaureM** [comment]
Point sur la domiciliation

2 catégories d’organismes domiciliataires :
•	les centres communaux et intercommunaux d’action sociale (CCas et CIas)  obligation légale
•	les organismes agréés. (associations et autres organismes)
La liste de ces organismes est disponible auprès des mairies (un tiers seulement des CCAS dit disposer d'une liste de ces organismes mise à jour et communiquée par le Préfet. )

Au moment de la demande, les CCAS procèdent à un entretien avec l’intéressé au cours duquel ce dernier reçoit une information complète sur ses droits et obligations en matière de domiciliation. Il a lieu le jour même de la demande, sinon délai moyen de moins de 5 jours
Un formulaire unique : l’attestation d’élection de domicile / CERFA n°13482-02 
Durée de validité : une année. 

Le public concerné: les personnes qui vivent de façon itinérante, hébergées de façon très temporaire par des tiers, celles qui recourent à des centres d’hébergement d’urgence et les gens du voyage

Estimation du nb de personnes concernées: L'INSEE évalue à 200 000 le nombre de personnes sans domicile fixe en France + 317 884 gens du voyage + 65 000 personnes détenues + 60 000 demandeurs d'asile et 220 000 bénéficiaires de l'AME

Enquête UNCCAS
On compte 93 000 domiciliations actives fin 2013.
 • Les trois quarts des CCAS pratiquent la domiciliation  (surtout dans les plus grandes villes) 
• 82% des CCAS pratiquent la domiciliation pour permettre l’obtention d’une prestation ou d’un minimum social.

**Comment by MattiSG** [comment]
https://twitter.com/mesaides/status/613625925197012992
