### ISSUE TITLE
Reporter erreur - Unauthorized

### ISSUE THREAD

**Issue by matheod** [sgmap/mes-aides-ui#89]
Bonsoir,

Je testais le service rapidement en appuyant un peu sur tout et sur la page " Résultats de votre simulation", lorsque j'ai cliqué sur le "Cliquez ici" de : 

>Vous pensez que le droit applicable à votre situation n'est pas correctement estimé par ce simulateur ? 
>Vous êtes en mesure de nous fournir une information précise sur vos droits ? 
>Cliquez ici.

J'ai eu le message d'erreur (en alert) "Unauthorized".

**Comment by fpagnoux** [comment]
Bonjour, 

Ce message apparaît lorsque l'on tente de créer un test sans être authentifié. Nous travaillons dessus en ce moment pour avoir quelque chose de plus sympathique que cette pop up un peu violente ;)

https://github.com/sgmap/ludwig-ui/pull/36
Ce sera mis en production rapidement je pense

**Comment by matheod** [comment]
Ok, parfais :)

**Comment by fpagnoux** [comment]
Nous venons de mettre en production une solution. N'hésitez pas à nous donner un retour !

**Comment by matheod** [comment]
Ca fonctionne, sauf un petit soucis : le bouton précédent ne fonctionne plus (la page immédiatement précédente semble rediriger vers la page de login) (sur google chrome).

Un autre petit soucis mais alors là c'est chercher la perfection :D , si on retourne vraiment à la page  "Résultats de votre simulation" en utilisant le clic droit sur le bouton précédent, et qu'on reclic ensuite sur le lien pour reporter une erreur, on a de nouveau le Unauthorised qui s'affiche.

**Comment by fpagnoux** [comment]
Merci pour le retour ! 

Oui, on passe par une redirection, donc le bouton précédent ne fonctionne pas. Je note le point d'amélioration, mais je pense que dans l'immédiat on va s'en contenter.

Pour le deuxième problème, je n'ai pas réussi à le reproduire, ce n'est pas un problème de cache ?

**Comment by matheod** [comment]
Le deuxième problème était bien un problème de cache.
