### ISSUE TITLE
Restaurer le code postal et la ville au retour à une page précédente

### ISSUE THREAD

**Issue by matheod** [sgmap/mes-aides-ui#92]
Si l'on remplis le formule, puis si l'on clic sur Modifier à coté de Votre logement (à droite), tout les champs sont restaurés, sauf le champs Code postal et ville qui est vide.

**Comment by MattiSG** [comment]
Bonjour @matheod et merci pour ce retour de bug !

Tu pourras suivre l'avancement de sa correction à travers les tags attribués à cette issue, selon notre [processus de travail](https://github.com/sgmap/mes-aides-ui/blob/master/CONTRIBUTING.md#processus). Nous te notifierons évidemment lorsqu'elle sera résolue.

Bonne journée !
Matti

**Comment by matheod** [comment]
Pas de soucis :)

(Par chance) Je n'ai pas besoin de ce site, mais c'est une très bonne initiative, félicitation :)

**Comment by MattiSG** [comment]
Merci  :)

**Comment by MattiSG** [comment]
Après un an et demi, ce problème non prioritaire a été traité  :wink:

Merci de nous l'avoir signalé @matheod ! 😄
