### ISSUE TITLE
Rendre visible les erreurs à l'entrée des revenus n-2

### ISSUE THREAD

**Issue by matheod** [sgmap/mes-aides-ui#93]
Sur la page Vos revenus imposables en 2013, si l'on entre un nombre négatif (on peut supposer qu'une personne appuis par erreur sur le - en même temps qu'elle appuis sur le 9), alors deux cas : 
- Quand on appuie sur valider rien ne se passe (à cause d'une erreur 500).
- Quand on appuie sur valider on arrive sur la page "Votre revenu fiscal de référence" (c'est le cas si on a mis une personne à charge) et là quand on appuis sur valider rien ne se passe, et ce même si on a mis une valeur juste sur la page "Votre revenu fiscal de référence" (à cause d'une erreur 500) (et là la personne ne se rendra pas compte du - en trop vu que ce n'est plus la même page).

**Comment by MattiSG** [comment]
Il y a effectivement un problème dans l'interface si rien ne se passe.

Ceci étant dit, qu'est-ce qui t'a poussé à essayer d'entrer un nombre négatif ? As-tu toi-même appuyé par erreur sur le `-` en même temps que le `9` ?

**Comment by matheod** [comment]
Non j'ai juste testé ce qui avait des chances de poser des problèmes (nombre négatifs, à virgule, etc.). Pour ça que c'est un problème qui a très peu de chance d'arriver (donc peu urgent), mais je signale tout de même car ça peut arriver justement avec cette histoire de - en même temps que le 9. C'est plus dans l'idée de faire un truc parfait quoi :)

**Comment by MattiSG** [comment]
Ok, merci. On focalise sur la visibilité des erreurs, qui est effectivement un défaut. La gestion des cas volontairement aberrants n'est pas une priorité tant que non avérés par un retour utilisateur réel.
J'ai renommé l'issue en conséquence.

**Comment by MattiSG** [comment]
@fpagnoux Corrigé via #141 ?

**Comment by fpagnoux** [comment]
Si oui pas volontairement, mais je n'arrive pas à reproduire le bug chez moi en tout cas

**Comment by fpagnoux** [comment]
Dans le comportement actuel, le simulateur ignore apparemment les valeurs négatives, sans pour autant mettre de message d'erreur. Il serait peut-être mieux d’empêcher la validation du premier formulaire en cas de valeur négative, non ?

**Comment by MattiSG** [comment]
On peut ajouter un `min="0"` mais cette issue ne pourra être fermée que quand les erreurs seront rendues visibles.
Tant pis, ce sera pour plus tard !
