### ISSUE TITLE
Ressources de votre foyer - Nombres décimaux arrondis lors de la restauration

### ISSUE THREAD

**Issue by matheod** [sgmap/mes-aides-ui#94]
Sur la page Ressources de votre foyer, si l'on entre un nombre à virgule, et qu'on y retourne par la suite via le menu de droite en appuyant sur Modifier à côté de "Vos ressources", les nombres à virgule se transforment en nombre entier (arrondis).

**Comment by MattiSG** [comment]
Les montants réellement pris en compte sont de toute façon arrondis, mais l'interface peut effectivement perturber. L'arrondi devrait avoir lieu lors de l'envoi des données et non lors du stockage pour restauration.

Tu pourras suivre l'avancement de l'implémentation de cette amélioration à travers les tags attribués à cette issue, selon notre [processus de travail](https://github.com/sgmap/mes-aides-ui/blob/master/CONTRIBUTING.md#processus). Nous te notifierons évidemment lorsqu'elle sera disponible, mais elle n'est pas prioritaire aujourd'hui.

**Comment by MattiSG** [comment]
Bonjour @matheod !

Un an plus tard, grâce à #328, nous avons corrigé ce problème  😉
Merci de nous l'avoir indiqué !

![ressources-virgule](https://cloud.githubusercontent.com/assets/222463/17523252/3af345be-5e5a-11e6-8894-7f38546bc73d.gif)
