### ISSUE TITLE
Capturer la substitution des ressources professionnelles interrompues

### ISSUE THREAD

**Issue by fpagnoux** [sgmap/mes-aides-ui#96]
Si un demandeur indique qu'il ne continuera pas à percevoir une ressource le mois courant, on ne peut pas, avec l'interface actuelle, savoir si ce revenu sera ou non substitué. 

Ceci  a un impact sur les neutralisations et abattement pour les calculs du RSA et de l'ASS

Suggestion à débattre : Quand le demandeur décoche cette case, lui demander s'il va recevoir un revenu de substitution (retraite, ARE, IJSS) ou non.

**Comment by Anne-LaureM** [comment]
Connected to #22.

**Comment by MattiSG** [comment]
Fixed via #261.
